/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.ServiceTime;
import ch.sbb.api.smapi.osdm.journey.client.StopCallStatus;
import ch.sbb.api.smapi.osdm.journey.client.StopPlaceRef;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Describes the situation at a stop or station at which the passenger alights from a Leg of a trip including time-related information. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class Alight {
  @JsonProperty("stopPlaceRef")
  private StopPlaceRef stopPlaceRef = null;

  @JsonProperty("stopPlaceName")
  private String stopPlaceName = null;

  @JsonProperty("plannedStopPointName")
  private String plannedStopPointName = null;

  @JsonProperty("estimatedStopPointName")
  private String estimatedStopPointName = null;

  @JsonProperty("serviceArrival")
  private ServiceTime serviceArrival = null;

  @JsonProperty("status")
  private StopCallStatus status = null;

  public Alight stopPlaceRef(StopPlaceRef stopPlaceRef) {
    this.stopPlaceRef = stopPlaceRef;
    return this;
  }

   /**
   * Get stopPlaceRef
   * @return stopPlaceRef
  **/
  public StopPlaceRef getStopPlaceRef() {
    return stopPlaceRef;
  }

  public void setStopPlaceRef(StopPlaceRef stopPlaceRef) {
    this.stopPlaceRef = stopPlaceRef;
  }

  public Alight stopPlaceName(String stopPlaceName) {
    this.stopPlaceName = stopPlaceName;
    return this;
  }

   /**
   * Get stopPlaceName
   * @return stopPlaceName
  **/
  public String getStopPlaceName() {
    return stopPlaceName;
  }

  public void setStopPlaceName(String stopPlaceName) {
    this.stopPlaceName = stopPlaceName;
  }

  public Alight plannedStopPointName(String plannedStopPointName) {
    this.plannedStopPointName = plannedStopPointName;
    return this;
  }

   /**
   * Name of the bay/quay/terminal where to board/alight from the vehicle. According to planned timetable. 
   * @return plannedStopPointName
  **/
  public String getPlannedStopPointName() {
    return plannedStopPointName;
  }

  public void setPlannedStopPointName(String plannedStopPointName) {
    this.plannedStopPointName = plannedStopPointName;
  }

  public Alight estimatedStopPointName(String estimatedStopPointName) {
    this.estimatedStopPointName = estimatedStopPointName;
    return this;
  }

   /**
   * Name of the bay/quay/terminal where to board the vehicle. As to the latest realtime status. 
   * @return estimatedStopPointName
  **/
  public String getEstimatedStopPointName() {
    return estimatedStopPointName;
  }

  public void setEstimatedStopPointName(String estimatedStopPointName) {
    this.estimatedStopPointName = estimatedStopPointName;
  }

  public Alight serviceArrival(ServiceTime serviceArrival) {
    this.serviceArrival = serviceArrival;
    return this;
  }

   /**
   * Get serviceArrival
   * @return serviceArrival
  **/
  public ServiceTime getServiceArrival() {
    return serviceArrival;
  }

  public void setServiceArrival(ServiceTime serviceArrival) {
    this.serviceArrival = serviceArrival;
  }

  public Alight status(StopCallStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public StopCallStatus getStatus() {
    return status;
  }

  public void setStatus(StopCallStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Alight alight = (Alight) o;
    return Objects.equals(this.stopPlaceRef, alight.stopPlaceRef) &&
        Objects.equals(this.stopPlaceName, alight.stopPlaceName) &&
        Objects.equals(this.plannedStopPointName, alight.plannedStopPointName) &&
        Objects.equals(this.estimatedStopPointName, alight.estimatedStopPointName) &&
        Objects.equals(this.serviceArrival, alight.serviceArrival) &&
        Objects.equals(this.status, alight.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stopPlaceRef, stopPlaceName, plannedStopPointName, estimatedStopPointName, serviceArrival, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Alight {\n");
    
    sb.append("    stopPlaceRef: ").append(toIndentedString(stopPlaceRef)).append("\n");
    sb.append("    stopPlaceName: ").append(toIndentedString(stopPlaceName)).append("\n");
    sb.append("    plannedStopPointName: ").append(toIndentedString(plannedStopPointName)).append("\n");
    sb.append("    estimatedStopPointName: ").append(toIndentedString(estimatedStopPointName)).append("\n");
    sb.append("    serviceArrival: ").append(toIndentedString(serviceArrival)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
