/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.ContinuousService;
import ch.sbb.api.smapi.osdm.journey.client.Quantity;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * A leg of a journey that is not bound to a timetable. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class ContinuousLeg {
  @JsonProperty("start")
  private OneOfContinuousLegStart start = null;

  @JsonProperty("end")
  private OneOfContinuousLegEnd end = null;

  @JsonProperty("service")
  private ContinuousService service = null;

  @JsonProperty("timeWindowStart")
  private OffsetDateTime timeWindowStart = null;

  @JsonProperty("timeWindowEnd")
  private OffsetDateTime timeWindowEnd = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("situationFullRefs")
  private List<String> situationFullRefs = null;

  @JsonProperty("co2Emission")
  private Quantity co2Emission = null;

  public ContinuousLeg start(OneOfContinuousLegStart start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  public OneOfContinuousLegStart getStart() {
    return start;
  }

  public void setStart(OneOfContinuousLegStart start) {
    this.start = start;
  }

  public ContinuousLeg end(OneOfContinuousLegEnd end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  public OneOfContinuousLegEnd getEnd() {
    return end;
  }

  public void setEnd(OneOfContinuousLegEnd end) {
    this.end = end;
  }

  public ContinuousLeg service(ContinuousService service) {
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  public ContinuousService getService() {
    return service;
  }

  public void setService(ContinuousService service) {
    this.service = service;
  }

  public ContinuousLeg timeWindowStart(OffsetDateTime timeWindowStart) {
    this.timeWindowStart = timeWindowStart;
    return this;
  }

   /**
   * Time at which window begins. 
   * @return timeWindowStart
  **/
  public OffsetDateTime getTimeWindowStart() {
    return timeWindowStart;
  }

  public void setTimeWindowStart(OffsetDateTime timeWindowStart) {
    this.timeWindowStart = timeWindowStart;
  }

  public ContinuousLeg timeWindowEnd(OffsetDateTime timeWindowEnd) {
    this.timeWindowEnd = timeWindowEnd;
    return this;
  }

   /**
   * Time at which window ends. 
   * @return timeWindowEnd
  **/
  public OffsetDateTime getTimeWindowEnd() {
    return timeWindowEnd;
  }

  public void setTimeWindowEnd(OffsetDateTime timeWindowEnd) {
    this.timeWindowEnd = timeWindowEnd;
  }

  public ContinuousLeg duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration of this leg according to user preferences like walk speed. 
   * @return duration
  **/
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public ContinuousLeg situationFullRefs(List<String> situationFullRefs) {
    this.situationFullRefs = situationFullRefs;
    return this;
  }

  public ContinuousLeg addSituationFullRefsItem(String situationFullRefsItem) {
    if (this.situationFullRefs == null) {
      this.situationFullRefs = new ArrayList<>();
    }
    this.situationFullRefs.add(situationFullRefsItem);
    return this;
  }

   /**
   * Get situationFullRefs
   * @return situationFullRefs
  **/
  public List<String> getSituationFullRefs() {
    return situationFullRefs;
  }

  public void setSituationFullRefs(List<String> situationFullRefs) {
    this.situationFullRefs = situationFullRefs;
  }

  public ContinuousLeg co2Emission(Quantity co2Emission) {
    this.co2Emission = co2Emission;
    return this;
  }

   /**
   * Get co2Emission
   * @return co2Emission
  **/
  public Quantity getCo2Emission() {
    return co2Emission;
  }

  public void setCo2Emission(Quantity co2Emission) {
    this.co2Emission = co2Emission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContinuousLeg continuousLeg = (ContinuousLeg) o;
    return Objects.equals(this.start, continuousLeg.start) &&
        Objects.equals(this.end, continuousLeg.end) &&
        Objects.equals(this.service, continuousLeg.service) &&
        Objects.equals(this.timeWindowStart, continuousLeg.timeWindowStart) &&
        Objects.equals(this.timeWindowEnd, continuousLeg.timeWindowEnd) &&
        Objects.equals(this.duration, continuousLeg.duration) &&
        Objects.equals(this.situationFullRefs, continuousLeg.situationFullRefs) &&
        Objects.equals(this.co2Emission, continuousLeg.co2Emission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end, service, timeWindowStart, timeWindowEnd, duration, situationFullRefs, co2Emission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContinuousLeg {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    timeWindowStart: ").append(toIndentedString(timeWindowStart)).append("\n");
    sb.append("    timeWindowEnd: ").append(toIndentedString(timeWindowEnd)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    situationFullRefs: ").append(toIndentedString(situationFullRefs)).append("\n");
    sb.append("    co2Emission: ").append(toIndentedString(co2Emission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
