/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.FareConnectionPointRef;
import ch.sbb.api.smapi.osdm.journey.client.GeoPosition;
import ch.sbb.api.smapi.osdm.journey.client.Link;
import ch.sbb.api.smapi.osdm.journey.client.Place;
import ch.sbb.api.smapi.osdm.journey.client.StationSet;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Connection point connecting two fare regimes. The connection is possible between stations of the two provided station sets. A legacy border point code (id) might be provided as an additional code within the stations (code list BORDER_POINT provided in URN). In case the connection point is a real station this station is indicated. In case the connection point is between stations for each side of the border real stations must be provided. Multiple sets of station can be provided in the rare case that the connection point connects more than two station (A-B and A-C). Multiple stations within a set at one side of the border might be provided in case of changes (new stations build near the border).  Providing the UIC code for the station is mandatory. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class FareConnectionPoint extends Place implements OneOfContinuousLegStart, OneOfContinuousLegEnd, OneOfPlaceResponsePlacesItems {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("stationSets")
  private List<StationSet> stationSets = new ArrayList<>();

  @JsonProperty("ref")
  private FareConnectionPointRef ref = null;

  public FareConnectionPoint name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FareConnectionPoint stationSets(List<StationSet> stationSets) {
    this.stationSets = stationSets;
    return this;
  }

  public FareConnectionPoint addStationSetsItem(StationSet stationSetsItem) {
    this.stationSets.add(stationSetsItem);
    return this;
  }

   /**
   * Get stationSets
   * @return stationSets
  **/
  public List<StationSet> getStationSets() {
    return stationSets;
  }

  public void setStationSets(List<StationSet> stationSets) {
    this.stationSets = stationSets;
  }

  public FareConnectionPoint ref(FareConnectionPointRef ref) {
    this.ref = ref;
    return this;
  }

   /**
   * Get ref
   * @return ref
  **/
  public FareConnectionPointRef getRef() {
    return ref;
  }

  public void setRef(FareConnectionPointRef ref) {
    this.ref = ref;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FareConnectionPoint fareConnectionPoint = (FareConnectionPoint) o;
    return Objects.equals(this.name, fareConnectionPoint.name) &&
        Objects.equals(this.stationSets, fareConnectionPoint.stationSets) &&
        Objects.equals(this.ref, fareConnectionPoint.ref) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, stationSets, ref, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FareConnectionPoint {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    stationSets: ").append(toIndentedString(stationSets)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
