/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Attributes that are not valid on the whole service, but only on section of a trip made on a single mode without interchange between boarding and alighting. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class LegAttribute {
  @JsonProperty("text")
  private String text = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("fromStopSeqNumber")
  private Integer fromStopSeqNumber = null;

  @JsonProperty("toStopSeqNumber")
  private Integer toStopSeqNumber = null;

  public LegAttribute text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Text of the attribute to be shown to the user. 
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public LegAttribute code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Internal code of the attribute. Can be used for detection of double occurrences. Refers to Service Facilities / Leg Attributes from the Catalog of Code Lists 
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public LegAttribute fromStopSeqNumber(Integer fromStopSeqNumber) {
    this.fromStopSeqNumber = fromStopSeqNumber;
    return this;
  }

   /**
   * The attribute is valid from the stop point with this sequence number within the leg. If missing it is valid from the beginning of the leg. 
   * minimum: 0
   * @return fromStopSeqNumber
  **/
  public Integer getFromStopSeqNumber() {
    return fromStopSeqNumber;
  }

  public void setFromStopSeqNumber(Integer fromStopSeqNumber) {
    this.fromStopSeqNumber = fromStopSeqNumber;
  }

  public LegAttribute toStopSeqNumber(Integer toStopSeqNumber) {
    this.toStopSeqNumber = toStopSeqNumber;
    return this;
  }

   /**
   * The attribute is valid to the stop point (inclusively) with this sequence number within the leg. If missing it is valid to the end of the leg. 
   * minimum: 0
   * @return toStopSeqNumber
  **/
  public Integer getToStopSeqNumber() {
    return toStopSeqNumber;
  }

  public void setToStopSeqNumber(Integer toStopSeqNumber) {
    this.toStopSeqNumber = toStopSeqNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegAttribute legAttribute = (LegAttribute) o;
    return Objects.equals(this.text, legAttribute.text) &&
        Objects.equals(this.code, legAttribute.code) &&
        Objects.equals(this.fromStopSeqNumber, legAttribute.fromStopSeqNumber) &&
        Objects.equals(this.toStopSeqNumber, legAttribute.toStopSeqNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, code, fromStopSeqNumber, toStopSeqNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegAttribute {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    fromStopSeqNumber: ").append(toIndentedString(fromStopSeqNumber)).append("\n");
    sb.append("    toStopSeqNumber: ").append(toIndentedString(toStopSeqNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
