/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.Mode;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * List of public transport modes to include or exclude. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class ModeFilter {
  @JsonProperty("exclude")
  private Boolean exclude = null;

  @JsonProperty("transportModes")
  private List<Mode> transportModes = null;

  public ModeFilter exclude(Boolean exclude) {
    this.exclude = exclude;
    return this;
  }

   /**
   * Whether modes in list are to include or exclude from search. 
   * @return exclude
  **/
  public Boolean isExclude() {
    return exclude;
  }

  public void setExclude(Boolean exclude) {
    this.exclude = exclude;
  }

  public ModeFilter transportModes(List<Mode> transportModes) {
    this.transportModes = transportModes;
    return this;
  }

  public ModeFilter addTransportModesItem(Mode transportModesItem) {
    if (this.transportModes == null) {
      this.transportModes = new ArrayList<>();
    }
    this.transportModes.add(transportModesItem);
    return this;
  }

   /**
   * List of Transport modes to include/exclude. 
   * @return transportModes
  **/
  public List<Mode> getTransportModes() {
    return transportModes;
  }

  public void setTransportModes(List<Mode> transportModes) {
    this.transportModes = transportModes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModeFilter modeFilter = (ModeFilter) o;
    return Objects.equals(this.exclude, modeFilter.exclude) &&
        Objects.equals(this.transportModes, modeFilter.transportModes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exclude, transportModes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModeFilter {\n");
    
    sb.append("    exclude: ").append(toIndentedString(exclude)).append("\n");
    sb.append("    transportModes: ").append(toIndentedString(transportModes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
