/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.PointOfInterestCategory;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Filter POIs by category. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class PointOfInterestFilter {
  @JsonProperty("exclude")
  private Boolean exclude = null;

  @JsonProperty("pointOfInterestCategory")
  private List<PointOfInterestCategory> pointOfInterestCategory = null;

  public PointOfInterestFilter exclude(Boolean exclude) {
    this.exclude = exclude;
    return this;
  }

   /**
   * Whether carriers are to be included or excluded from the filtering. 
   * @return exclude
  **/
  public Boolean isExclude() {
    return exclude;
  }

  public void setExclude(Boolean exclude) {
    this.exclude = exclude;
  }

  public PointOfInterestFilter pointOfInterestCategory(List<PointOfInterestCategory> pointOfInterestCategory) {
    this.pointOfInterestCategory = pointOfInterestCategory;
    return this;
  }

  public PointOfInterestFilter addPointOfInterestCategoryItem(PointOfInterestCategory pointOfInterestCategoryItem) {
    if (this.pointOfInterestCategory == null) {
      this.pointOfInterestCategory = new ArrayList<>();
    }
    this.pointOfInterestCategory.add(pointOfInterestCategoryItem);
    return this;
  }

   /**
   * These POI categories can be used to filter POIs. If more than one is given the filtering is by logical &#x27;OR&#x27; (when Exclude&#x3D;FALSE) and logical &#x27;AND&#x27; (when Exclude&#x3D;TRUE). 
   * @return pointOfInterestCategory
  **/
  public List<PointOfInterestCategory> getPointOfInterestCategory() {
    return pointOfInterestCategory;
  }

  public void setPointOfInterestCategory(List<PointOfInterestCategory> pointOfInterestCategory) {
    this.pointOfInterestCategory = pointOfInterestCategory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointOfInterestFilter pointOfInterestFilter = (PointOfInterestFilter) o;
    return Objects.equals(this.exclude, pointOfInterestFilter.exclude) &&
        Objects.equals(this.pointOfInterestCategory, pointOfInterestFilter.pointOfInterestCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exclude, pointOfInterestCategory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointOfInterestFilter {\n");
    
    sb.append("    exclude: ").append(toIndentedString(exclude)).append("\n");
    sb.append("    pointOfInterestCategory: ").append(toIndentedString(pointOfInterestCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
