/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.OsmTag;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * A categorization of points of interest in respect of the activities undertaken at them (defined by key-value-pairs). Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class PointOfInterestCategory {
  @JsonProperty("osmTags")
  private List<OsmTag> osmTags = null;

  @JsonProperty("pointOfInterestClassifications")
  private List<String> pointOfInterestClassifications = null;

  public PointOfInterestCategory osmTags(List<OsmTag> osmTags) {
    this.osmTags = osmTags;
    return this;
  }

  public PointOfInterestCategory addOsmTagsItem(OsmTag osmTagsItem) {
    if (this.osmTags == null) {
      this.osmTags = new ArrayList<>();
    }
    this.osmTags.add(osmTagsItem);
    return this;
  }

   /**
   * Open Street Map tag structure (key-value) 
   * @return osmTags
  **/
  public List<OsmTag> getOsmTags() {
    return osmTags;
  }

  public void setOsmTags(List<OsmTag> osmTags) {
    this.osmTags = osmTags;
  }

  public PointOfInterestCategory pointOfInterestClassifications(List<String> pointOfInterestClassifications) {
    this.pointOfInterestClassifications = pointOfInterestClassifications;
    return this;
  }

  public PointOfInterestCategory addPointOfInterestClassificationsItem(String pointOfInterestClassificationsItem) {
    if (this.pointOfInterestClassifications == null) {
      this.pointOfInterestClassifications = new ArrayList<>();
    }
    this.pointOfInterestClassifications.add(pointOfInterestClassificationsItem);
    return this;
  }

   /**
   * Classification of the POI (when it is not from OSM). The codification of the classification Id may include de codification source (for example &#x27;IGN:[classificationCode]&#x27;) 
   * @return pointOfInterestClassifications
  **/
  public List<String> getPointOfInterestClassifications() {
    return pointOfInterestClassifications;
  }

  public void setPointOfInterestClassifications(List<String> pointOfInterestClassifications) {
    this.pointOfInterestClassifications = pointOfInterestClassifications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointOfInterestCategory pointOfInterestCategory = (PointOfInterestCategory) o;
    return Objects.equals(this.osmTags, pointOfInterestCategory.osmTags) &&
        Objects.equals(this.pointOfInterestClassifications, pointOfInterestCategory.pointOfInterestClassifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(osmTags, pointOfInterestClassifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointOfInterestCategory {\n");
    
    sb.append("    osmTags: ").append(toIndentedString(osmTags)).append("\n");
    sb.append("    pointOfInterestClassifications: ").append(toIndentedString(pointOfInterestClassifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
