/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Problem Details for HTTP APIs (RFC 7807) defines a &#x27;problem detail&#x27; as a way to carry machine-readable details of errors in a HTTP response to avoid the need to define new error response formats for HTTP APIs. See: https://tools.ietf.org/html/rfc7807 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class Problem {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("detail")
  private String detail = null;

  @JsonProperty("instance")
  private String instance = null;

  public Problem code(String code) {
    this.code = code;
    return this;
  }

   /**
   * optional in version 3.1, will be made mandatory in upcoming releases 
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Problem type(String type) {
    this.type = type;
    return this;
  }

   /**
   * An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML). 
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Problem title(String title) {
    this.title = title;
    return this;
  }

   /**
   * A short, summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized); 
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Problem status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * The HTTP status code generated by the origin server for this occurrence of the problem. 
   * minimum: 100
   * maximum: 599
   * @return status
  **/
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Problem detail(String detail) {
    this.detail = detail;
    return this;
  }

   /**
   * A human readable explanation specific to this occurrence of the problem. 
   * @return detail
  **/
  public String getDetail() {
    return detail;
  }

  public void setDetail(String detail) {
    this.detail = detail;
  }

  public Problem instance(String instance) {
    this.instance = instance;
    return this;
  }

   /**
   * An absolute URI that identifies the specific occurrence of the problem. 
   * @return instance
  **/
  public String getInstance() {
    return instance;
  }

  public void setInstance(String instance) {
    this.instance = instance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Problem problem = (Problem) o;
    return Objects.equals(this.code, problem.code) &&
        Objects.equals(this.type, problem.type) &&
        Objects.equals(this.title, problem.title) &&
        Objects.equals(this.status, problem.status) &&
        Objects.equals(this.detail, problem.detail) &&
        Objects.equals(this.instance, problem.instance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, type, title, status, detail, instance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Problem {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
