/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * This property can be used in case a return trip is being requested. This will allow to benefit from return-specific fares or product 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class ReturnSearchParameters {
  @JsonProperty("inwardReturnDate")
  private String inwardReturnDate = null;

  @JsonProperty("outwardOfferIds")
  private List<String> outwardOfferIds = null;

  @JsonProperty("outwardOfferTag")
  private String outwardOfferTag = null;

  public ReturnSearchParameters inwardReturnDate(String inwardReturnDate) {
    this.inwardReturnDate = inwardReturnDate;
    return this;
  }

   /**
   * Needs to be provided when creating the collection of outward travels so that the provider knows when a return travel can be expected and propose appropriate product and fares. 
   * @return inwardReturnDate
  **/
  public String getInwardReturnDate() {
    return inwardReturnDate;
  }

  public void setInwardReturnDate(String inwardReturnDate) {
    this.inwardReturnDate = inwardReturnDate;
  }

  public ReturnSearchParameters outwardOfferIds(List<String> outwardOfferIds) {
    this.outwardOfferIds = outwardOfferIds;
    return this;
  }

  public ReturnSearchParameters addOutwardOfferIdsItem(String outwardOfferIdsItem) {
    if (this.outwardOfferIds == null) {
      this.outwardOfferIds = new ArrayList<>();
    }
    this.outwardOfferIds.add(outwardOfferIdsItem);
    return this;
  }

   /**
   * Needs to be provided when creating the collection of inward travels so that the provider can relate the inward travels to the outward travels context. 
   * @return outwardOfferIds
  **/
  public List<String> getOutwardOfferIds() {
    return outwardOfferIds;
  }

  public void setOutwardOfferIds(List<String> outwardOfferIds) {
    this.outwardOfferIds = outwardOfferIds;
  }

  public ReturnSearchParameters outwardOfferTag(String outwardOfferTag) {
    this.outwardOfferTag = outwardOfferTag;
    return this;
  }

   /**
   * Needs to be provided when creating the collection of inward travels so that the provider knows what the outward offer is and and propose compatible offers only if desired or mandatory. 
   * @return outwardOfferTag
  **/
  public String getOutwardOfferTag() {
    return outwardOfferTag;
  }

  public void setOutwardOfferTag(String outwardOfferTag) {
    this.outwardOfferTag = outwardOfferTag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnSearchParameters returnSearchParameters = (ReturnSearchParameters) o;
    return Objects.equals(this.inwardReturnDate, returnSearchParameters.inwardReturnDate) &&
        Objects.equals(this.outwardOfferIds, returnSearchParameters.outwardOfferIds) &&
        Objects.equals(this.outwardOfferTag, returnSearchParameters.outwardOfferTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inwardReturnDate, outwardOfferIds, outwardOfferTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnSearchParameters {\n");
    
    sb.append("    inwardReturnDate: ").append(toIndentedString(inwardReturnDate)).append("\n");
    sb.append("    outwardOfferIds: ").append(toIndentedString(outwardOfferIds)).append("\n");
    sb.append("    outwardOfferTag: ").append(toIndentedString(outwardOfferTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
