/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Parameters which describe the current status of a dated vehicle journey. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class ServiceStatus {
  @JsonProperty("unplanned")
  private Boolean unplanned = null;

  @JsonProperty("cancelled")
  private Boolean cancelled = null;

  @JsonProperty("deviation")
  private Boolean deviation = null;

  @JsonProperty("occupancy")
  private String occupancy = null;

  public ServiceStatus unplanned(Boolean unplanned) {
    this.unplanned = unplanned;
    return this;
  }

   /**
   * Whether this trip is an additional one that has not been planned. 
   * @return unplanned
  **/
  public Boolean isUnplanned() {
    return unplanned;
  }

  public void setUnplanned(Boolean unplanned) {
    this.unplanned = unplanned;
  }

  public ServiceStatus cancelled(Boolean cancelled) {
    this.cancelled = cancelled;
    return this;
  }

   /**
   * Whether this trip is cancelled and will not be run. 
   * @return cancelled
  **/
  public Boolean isCancelled() {
    return cancelled;
  }

  public void setCancelled(Boolean cancelled) {
    this.cancelled = cancelled;
  }

  public ServiceStatus deviation(Boolean deviation) {
    this.deviation = deviation;
    return this;
  }

   /**
   * Whether this trip deviates from the planned service pattern. 
   * @return deviation
  **/
  public Boolean isDeviation() {
    return deviation;
  }

  public void setDeviation(Boolean deviation) {
    this.deviation = deviation;
  }

  public ServiceStatus occupancy(String occupancy) {
    this.occupancy = occupancy;
    return this;
  }

   /**
   * Passenger load status on vehicle. If omitted, not known. Equivalent to siri:OccupancyEnumeration which describes three values: &#x27;full&#x27;, &#x27;seatingAvailable&#x27; and &#x27;standingAvailable&#x27;. 
   * @return occupancy
  **/
  public String getOccupancy() {
    return occupancy;
  }

  public void setOccupancy(String occupancy) {
    this.occupancy = occupancy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceStatus serviceStatus = (ServiceStatus) o;
    return Objects.equals(this.unplanned, serviceStatus.unplanned) &&
        Objects.equals(this.cancelled, serviceStatus.cancelled) &&
        Objects.equals(this.deviation, serviceStatus.deviation) &&
        Objects.equals(this.occupancy, serviceStatus.occupancy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unplanned, cancelled, deviation, occupancy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceStatus {\n");
    
    sb.append("    unplanned: ").append(toIndentedString(unplanned)).append("\n");
    sb.append("    cancelled: ").append(toIndentedString(cancelled)).append("\n");
    sb.append("    deviation: ").append(toIndentedString(deviation)).append("\n");
    sb.append("    occupancy: ").append(toIndentedString(occupancy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
