/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Status properties for the vehicle call at this stop. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class StopCallStatus {
  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("requestStop")
  private Boolean requestStop = null;

  @JsonProperty("unplannedStop")
  private Boolean unplannedStop = null;

  @JsonProperty("notServicedStop")
  private Boolean notServicedStop = null;

  @JsonProperty("noBoardingAtStop")
  private Boolean noBoardingAtStop = null;

  @JsonProperty("noAlightingAtStop")
  private Boolean noAlightingAtStop = null;

  public StopCallStatus order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Sequence number of this stop in the service pattern of the journey. 
   * minimum: 0
   * @return order
  **/
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public StopCallStatus requestStop(Boolean requestStop) {
    this.requestStop = requestStop;
    return this;
  }

   /**
   * The vehicle journey calls at this stop only on demand. 
   * @return requestStop
  **/
  public Boolean isRequestStop() {
    return requestStop;
  }

  public void setRequestStop(Boolean requestStop) {
    this.requestStop = requestStop;
  }

  public StopCallStatus unplannedStop(Boolean unplannedStop) {
    this.unplannedStop = unplannedStop;
    return this;
  }

   /**
   * This stop has not been planned by the planning department. 
   * @return unplannedStop
  **/
  public Boolean isUnplannedStop() {
    return unplannedStop;
  }

  public void setUnplannedStop(Boolean unplannedStop) {
    this.unplannedStop = unplannedStop;
  }

  public StopCallStatus notServicedStop(Boolean notServicedStop) {
    this.notServicedStop = notServicedStop;
    return this;
  }

   /**
   * The vehicle will not call at this stop despite earlier planning. 
   * @return notServicedStop
  **/
  public Boolean isNotServicedStop() {
    return notServicedStop;
  }

  public void setNotServicedStop(Boolean notServicedStop) {
    this.notServicedStop = notServicedStop;
  }

  public StopCallStatus noBoardingAtStop(Boolean noBoardingAtStop) {
    this.noBoardingAtStop = noBoardingAtStop;
    return this;
  }

   /**
   * Boarding will not be allowed at this stop of this journey. 
   * @return noBoardingAtStop
  **/
  public Boolean isNoBoardingAtStop() {
    return noBoardingAtStop;
  }

  public void setNoBoardingAtStop(Boolean noBoardingAtStop) {
    this.noBoardingAtStop = noBoardingAtStop;
  }

  public StopCallStatus noAlightingAtStop(Boolean noAlightingAtStop) {
    this.noAlightingAtStop = noAlightingAtStop;
    return this;
  }

   /**
   * Alighting will not be allowed at this stop of this journey. 
   * @return noAlightingAtStop
  **/
  public Boolean isNoAlightingAtStop() {
    return noAlightingAtStop;
  }

  public void setNoAlightingAtStop(Boolean noAlightingAtStop) {
    this.noAlightingAtStop = noAlightingAtStop;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopCallStatus stopCallStatus = (StopCallStatus) o;
    return Objects.equals(this.order, stopCallStatus.order) &&
        Objects.equals(this.requestStop, stopCallStatus.requestStop) &&
        Objects.equals(this.unplannedStop, stopCallStatus.unplannedStop) &&
        Objects.equals(this.notServicedStop, stopCallStatus.notServicedStop) &&
        Objects.equals(this.noBoardingAtStop, stopCallStatus.noBoardingAtStop) &&
        Objects.equals(this.noAlightingAtStop, stopCallStatus.noAlightingAtStop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, requestStop, unplannedStop, notServicedStop, noBoardingAtStop, noAlightingAtStop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopCallStatus {\n");
    
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    requestStop: ").append(toIndentedString(requestStop)).append("\n");
    sb.append("    unplannedStop: ").append(toIndentedString(unplannedStop)).append("\n");
    sb.append("    notServicedStop: ").append(toIndentedString(notServicedStop)).append("\n");
    sb.append("    noBoardingAtStop: ").append(toIndentedString(noBoardingAtStop)).append("\n");
    sb.append("    noAlightingAtStop: ").append(toIndentedString(noAlightingAtStop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
