/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.Quantity;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * A leg which links other legs of a trip where a transfer between different places is required. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class TransferLeg {
  @JsonProperty("continuousMode")
  private String continuousMode = null;

  @JsonProperty("transferMode")
  private String transferMode = null;

  @JsonProperty("start")
  private OneOfTransferLegStart start = null;

  @JsonProperty("end")
  private OneOfTransferLegEnd end = null;

  @JsonProperty("timeWindowStart")
  private OffsetDateTime timeWindowStart = null;

  @JsonProperty("timeWindowEnd")
  private OffsetDateTime timeWindowEnd = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("situationFullRefs")
  private List<String> situationFullRefs = null;

  @JsonProperty("co2Emission")
  private Quantity co2Emission = null;

  public TransferLeg continuousMode(String continuousMode) {
    this.continuousMode = continuousMode;
    return this;
  }

   /**
   * Types of modes that run at any time without a timetable. Provided by OJP. 
   * @return continuousMode
  **/
  public String getContinuousMode() {
    return continuousMode;
  }

  public void setContinuousMode(String continuousMode) {
    this.continuousMode = continuousMode;
  }

  public TransferLeg transferMode(String transferMode) {
    this.transferMode = transferMode;
    return this;
  }

   /**
   * Modes dedicated to perform transfers. Provided by OJP. 
   * @return transferMode
  **/
  public String getTransferMode() {
    return transferMode;
  }

  public void setTransferMode(String transferMode) {
    this.transferMode = transferMode;
  }

  public TransferLeg start(OneOfTransferLegStart start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  public OneOfTransferLegStart getStart() {
    return start;
  }

  public void setStart(OneOfTransferLegStart start) {
    this.start = start;
  }

  public TransferLeg end(OneOfTransferLegEnd end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  public OneOfTransferLegEnd getEnd() {
    return end;
  }

  public void setEnd(OneOfTransferLegEnd end) {
    this.end = end;
  }

  public TransferLeg timeWindowStart(OffsetDateTime timeWindowStart) {
    this.timeWindowStart = timeWindowStart;
    return this;
  }

   /**
   * Time at which window begins. 
   * @return timeWindowStart
  **/
  public OffsetDateTime getTimeWindowStart() {
    return timeWindowStart;
  }

  public void setTimeWindowStart(OffsetDateTime timeWindowStart) {
    this.timeWindowStart = timeWindowStart;
  }

  public TransferLeg timeWindowEnd(OffsetDateTime timeWindowEnd) {
    this.timeWindowEnd = timeWindowEnd;
    return this;
  }

   /**
   * Time at which window ends. 
   * @return timeWindowEnd
  **/
  public OffsetDateTime getTimeWindowEnd() {
    return timeWindowEnd;
  }

  public void setTimeWindowEnd(OffsetDateTime timeWindowEnd) {
    this.timeWindowEnd = timeWindowEnd;
  }

  public TransferLeg duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Overall duration of this interchange. 
   * @return duration
  **/
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public TransferLeg situationFullRefs(List<String> situationFullRefs) {
    this.situationFullRefs = situationFullRefs;
    return this;
  }

  public TransferLeg addSituationFullRefsItem(String situationFullRefsItem) {
    if (this.situationFullRefs == null) {
      this.situationFullRefs = new ArrayList<>();
    }
    this.situationFullRefs.add(situationFullRefsItem);
    return this;
  }

   /**
   * Get situationFullRefs
   * @return situationFullRefs
  **/
  public List<String> getSituationFullRefs() {
    return situationFullRefs;
  }

  public void setSituationFullRefs(List<String> situationFullRefs) {
    this.situationFullRefs = situationFullRefs;
  }

  public TransferLeg co2Emission(Quantity co2Emission) {
    this.co2Emission = co2Emission;
    return this;
  }

   /**
   * Get co2Emission
   * @return co2Emission
  **/
  public Quantity getCo2Emission() {
    return co2Emission;
  }

  public void setCo2Emission(Quantity co2Emission) {
    this.co2Emission = co2Emission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferLeg transferLeg = (TransferLeg) o;
    return Objects.equals(this.continuousMode, transferLeg.continuousMode) &&
        Objects.equals(this.transferMode, transferLeg.transferMode) &&
        Objects.equals(this.start, transferLeg.start) &&
        Objects.equals(this.end, transferLeg.end) &&
        Objects.equals(this.timeWindowStart, transferLeg.timeWindowStart) &&
        Objects.equals(this.timeWindowEnd, transferLeg.timeWindowEnd) &&
        Objects.equals(this.duration, transferLeg.duration) &&
        Objects.equals(this.situationFullRefs, transferLeg.situationFullRefs) &&
        Objects.equals(this.co2Emission, transferLeg.co2Emission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(continuousMode, transferMode, start, end, timeWindowStart, timeWindowEnd, duration, situationFullRefs, co2Emission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferLeg {\n");
    
    sb.append("    continuousMode: ").append(toIndentedString(continuousMode)).append("\n");
    sb.append("    transferMode: ").append(toIndentedString(transferMode)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    timeWindowStart: ").append(toIndentedString(timeWindowStart)).append("\n");
    sb.append("    timeWindowEnd: ").append(toIndentedString(timeWindowEnd)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    situationFullRefs: ").append(toIndentedString(situationFullRefs)).append("\n");
    sb.append("    co2Emission: ").append(toIndentedString(co2Emission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
