/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.CarrierFilter;
import ch.sbb.api.smapi.osdm.journey.client.ModeFilter;
import ch.sbb.api.smapi.osdm.journey.client.ServiceBrandFilter;
import ch.sbb.api.smapi.osdm.journey.client.VehicleFilter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Data to be included/excluded from search, f.e. modes, carriers. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class TripDataFilter {
  @JsonProperty("ptModeFilter")
  private ModeFilter ptModeFilter = null;

  @JsonProperty("carrierFilter")
  private CarrierFilter carrierFilter = null;

  @JsonProperty("serviceBrandFilter")
  private ServiceBrandFilter serviceBrandFilter = null;

  @JsonProperty("vehicleFilter")
  private VehicleFilter vehicleFilter = null;

  public TripDataFilter ptModeFilter(ModeFilter ptModeFilter) {
    this.ptModeFilter = ptModeFilter;
    return this;
  }

   /**
   * Get ptModeFilter
   * @return ptModeFilter
  **/
  public ModeFilter getPtModeFilter() {
    return ptModeFilter;
  }

  public void setPtModeFilter(ModeFilter ptModeFilter) {
    this.ptModeFilter = ptModeFilter;
  }

  public TripDataFilter carrierFilter(CarrierFilter carrierFilter) {
    this.carrierFilter = carrierFilter;
    return this;
  }

   /**
   * Get carrierFilter
   * @return carrierFilter
  **/
  public CarrierFilter getCarrierFilter() {
    return carrierFilter;
  }

  public void setCarrierFilter(CarrierFilter carrierFilter) {
    this.carrierFilter = carrierFilter;
  }

  public TripDataFilter serviceBrandFilter(ServiceBrandFilter serviceBrandFilter) {
    this.serviceBrandFilter = serviceBrandFilter;
    return this;
  }

   /**
   * Get serviceBrandFilter
   * @return serviceBrandFilter
  **/
  public ServiceBrandFilter getServiceBrandFilter() {
    return serviceBrandFilter;
  }

  public void setServiceBrandFilter(ServiceBrandFilter serviceBrandFilter) {
    this.serviceBrandFilter = serviceBrandFilter;
  }

  public TripDataFilter vehicleFilter(VehicleFilter vehicleFilter) {
    this.vehicleFilter = vehicleFilter;
    return this;
  }

   /**
   * Get vehicleFilter
   * @return vehicleFilter
  **/
  public VehicleFilter getVehicleFilter() {
    return vehicleFilter;
  }

  public void setVehicleFilter(VehicleFilter vehicleFilter) {
    this.vehicleFilter = vehicleFilter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripDataFilter tripDataFilter = (TripDataFilter) o;
    return Objects.equals(this.ptModeFilter, tripDataFilter.ptModeFilter) &&
        Objects.equals(this.carrierFilter, tripDataFilter.carrierFilter) &&
        Objects.equals(this.serviceBrandFilter, tripDataFilter.serviceBrandFilter) &&
        Objects.equals(this.vehicleFilter, tripDataFilter.vehicleFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ptModeFilter, carrierFilter, serviceBrandFilter, vehicleFilter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripDataFilter {\n");
    
    sb.append("    ptModeFilter: ").append(toIndentedString(ptModeFilter)).append("\n");
    sb.append("    carrierFilter: ").append(toIndentedString(carrierFilter)).append("\n");
    sb.append("    serviceBrandFilter: ").append(toIndentedString(serviceBrandFilter)).append("\n");
    sb.append("    vehicleFilter: ").append(toIndentedString(vehicleFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
