/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.NotVia;
import ch.sbb.api.smapi.osdm.journey.client.ReturnSearchParameters;
import ch.sbb.api.smapi.osdm.journey.client.TripParameters;
import ch.sbb.api.smapi.osdm.journey.client.TripVia;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * request for trips 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class TripSearchCriteria {
  @JsonProperty("departureTime")
  private String departureTime = null;

  @JsonProperty("arrivalTime")
  private String arrivalTime = null;

  @JsonProperty("origin")
  private OneOfTripSearchCriteriaOrigin origin = null;

  @JsonProperty("destination")
  private OneOfTripSearchCriteriaDestination destination = null;

  @JsonProperty("vias")
  private List<TripVia> vias = null;

  @JsonProperty("parameters")
  private TripParameters parameters = null;

  /**
   * Influences whether referenced resources are returned in full or as references only. Proposed default ALL 
   */
  public enum EmbedEnum {
    ALL("ALL"),
    TRIPS("TRIPS"),
    TRIPSUMMARIES("TRIPSUMMARIES"),
    NONE("NONE");

    private String value;

    EmbedEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EmbedEnum fromValue(String input) {
      for (EmbedEnum b : EmbedEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("embed")
  private List<EmbedEnum> embed = null;

  @JsonProperty("returnSearchParameters")
  private ReturnSearchParameters returnSearchParameters = null;

  @JsonProperty("notVias")
  private List<NotVia> notVias = null;

  public TripSearchCriteria departureTime(String departureTime) {
    this.departureTime = departureTime;
    return this;
  }

   /**
   * Needs to in local date time format. 
   * @return departureTime
  **/
  public String getDepartureTime() {
    return departureTime;
  }

  public void setDepartureTime(String departureTime) {
    this.departureTime = departureTime;
  }

  public TripSearchCriteria arrivalTime(String arrivalTime) {
    this.arrivalTime = arrivalTime;
    return this;
  }

   /**
   * Needs to in local date time format. If arrival time is provided the departure time must be omitted. 
   * @return arrivalTime
  **/
  public String getArrivalTime() {
    return arrivalTime;
  }

  public void setArrivalTime(String arrivalTime) {
    this.arrivalTime = arrivalTime;
  }

  public TripSearchCriteria origin(OneOfTripSearchCriteriaOrigin origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin
  **/
  public OneOfTripSearchCriteriaOrigin getOrigin() {
    return origin;
  }

  public void setOrigin(OneOfTripSearchCriteriaOrigin origin) {
    this.origin = origin;
  }

  public TripSearchCriteria destination(OneOfTripSearchCriteriaDestination destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  public OneOfTripSearchCriteriaDestination getDestination() {
    return destination;
  }

  public void setDestination(OneOfTripSearchCriteriaDestination destination) {
    this.destination = destination;
  }

  public TripSearchCriteria vias(List<TripVia> vias) {
    this.vias = vias;
    return this;
  }

  public TripSearchCriteria addViasItem(TripVia viasItem) {
    if (this.vias == null) {
      this.vias = new ArrayList<>();
    }
    this.vias.add(viasItem);
    return this;
  }

   /**
   * Ordered series of points where the journey must pass through. If more than one via point is given all of them must be obeyed - in the correct order. The server is allowed to replace a via stop by equivalent stops.  TripDataFilters given at a via apply to the section after that via. To apply a TripDataFilter for  the first section (between the origin and the first via), use the TripDataFilter within the TripParameters structure. 
   * @return vias
  **/
  public List<TripVia> getVias() {
    return vias;
  }

  public void setVias(List<TripVia> vias) {
    this.vias = vias;
  }

  public TripSearchCriteria parameters(TripParameters parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  public TripParameters getParameters() {
    return parameters;
  }

  public void setParameters(TripParameters parameters) {
    this.parameters = parameters;
  }

  public TripSearchCriteria embed(List<EmbedEnum> embed) {
    this.embed = embed;
    return this;
  }

  public TripSearchCriteria addEmbedItem(EmbedEnum embedItem) {
    if (this.embed == null) {
      this.embed = new ArrayList<>();
    }
    this.embed.add(embedItem);
    return this;
  }

   /**
   * Influences whether referenced resources are returned in full or as references only. Proposed default ALL 
   * @return embed
  **/
  public List<EmbedEnum> getEmbed() {
    return embed;
  }

  public void setEmbed(List<EmbedEnum> embed) {
    this.embed = embed;
  }

  public TripSearchCriteria returnSearchParameters(ReturnSearchParameters returnSearchParameters) {
    this.returnSearchParameters = returnSearchParameters;
    return this;
  }

   /**
   * Get returnSearchParameters
   * @return returnSearchParameters
  **/
  public ReturnSearchParameters getReturnSearchParameters() {
    return returnSearchParameters;
  }

  public void setReturnSearchParameters(ReturnSearchParameters returnSearchParameters) {
    this.returnSearchParameters = returnSearchParameters;
  }

  public TripSearchCriteria notVias(List<NotVia> notVias) {
    this.notVias = notVias;
    return this;
  }

  public TripSearchCriteria addNotViasItem(NotVia notViasItem) {
    if (this.notVias == null) {
      this.notVias = new ArrayList<>();
    }
    this.notVias.add(notViasItem);
    return this;
  }

   /**
   * Get notVias
   * @return notVias
  **/
  public List<NotVia> getNotVias() {
    return notVias;
  }

  public void setNotVias(List<NotVia> notVias) {
    this.notVias = notVias;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripSearchCriteria tripSearchCriteria = (TripSearchCriteria) o;
    return Objects.equals(this.departureTime, tripSearchCriteria.departureTime) &&
        Objects.equals(this.arrivalTime, tripSearchCriteria.arrivalTime) &&
        Objects.equals(this.origin, tripSearchCriteria.origin) &&
        Objects.equals(this.destination, tripSearchCriteria.destination) &&
        Objects.equals(this.vias, tripSearchCriteria.vias) &&
        Objects.equals(this.parameters, tripSearchCriteria.parameters) &&
        Objects.equals(this.embed, tripSearchCriteria.embed) &&
        Objects.equals(this.returnSearchParameters, tripSearchCriteria.returnSearchParameters) &&
        Objects.equals(this.notVias, tripSearchCriteria.notVias);
  }

  @Override
  public int hashCode() {
    return Objects.hash(departureTime, arrivalTime, origin, destination, vias, parameters, embed, returnSearchParameters, notVias);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripSearchCriteria {\n");
    
    sb.append("    departureTime: ").append(toIndentedString(departureTime)).append("\n");
    sb.append("    arrivalTime: ").append(toIndentedString(arrivalTime)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    vias: ").append(toIndentedString(vias)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    embed: ").append(toIndentedString(embed)).append("\n");
    sb.append("    returnSearchParameters: ").append(toIndentedString(returnSearchParameters)).append("\n");
    sb.append("    notVias: ").append(toIndentedString(notVias)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
