/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Base mobility options to be applied for both public and individual transport. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class TripMobilityFilter {
  @JsonProperty("bikeTransport")
  private Boolean bikeTransport = null;

  @JsonProperty("walkSpeed")
  private Integer walkSpeed = null;

  @JsonProperty("additionalTransferTime")
  private String additionalTransferTime = null;

  @JsonProperty("minimalTransferTime")
  private String minimalTransferTime = null;

  public TripMobilityFilter bikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
    return this;
  }

   /**
   * The user wants to carry a bike on public transport. 
   * @return bikeTransport
  **/
  public Boolean isBikeTransport() {
    return bikeTransport;
  }

  public void setBikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
  }

  public TripMobilityFilter walkSpeed(Integer walkSpeed) {
    this.walkSpeed = walkSpeed;
    return this;
  }

   /**
   * Deviation from average walk speed in percent. 100% percent is average speed. 
   * @return walkSpeed
  **/
  public Integer getWalkSpeed() {
    return walkSpeed;
  }

  public void setWalkSpeed(Integer walkSpeed) {
    this.walkSpeed = walkSpeed;
  }

  public TripMobilityFilter additionalTransferTime(String additionalTransferTime) {
    this.additionalTransferTime = additionalTransferTime;
    return this;
  }

   /**
   * Additional time added to all transfers (also to transfers between individual to public transport). 
   * @return additionalTransferTime
  **/
  public String getAdditionalTransferTime() {
    return additionalTransferTime;
  }

  public void setAdditionalTransferTime(String additionalTransferTime) {
    this.additionalTransferTime = additionalTransferTime;
  }

  public TripMobilityFilter minimalTransferTime(String minimalTransferTime) {
    this.minimalTransferTime = minimalTransferTime;
    return this;
  }

   /**
   * Get minimalTransferTime
   * @return minimalTransferTime
  **/
  public String getMinimalTransferTime() {
    return minimalTransferTime;
  }

  public void setMinimalTransferTime(String minimalTransferTime) {
    this.minimalTransferTime = minimalTransferTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripMobilityFilter tripMobilityFilter = (TripMobilityFilter) o;
    return Objects.equals(this.bikeTransport, tripMobilityFilter.bikeTransport) &&
        Objects.equals(this.walkSpeed, tripMobilityFilter.walkSpeed) &&
        Objects.equals(this.additionalTransferTime, tripMobilityFilter.additionalTransferTime) &&
        Objects.equals(this.minimalTransferTime, tripMobilityFilter.minimalTransferTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bikeTransport, walkSpeed, additionalTransferTime, minimalTransferTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripMobilityFilter {\n");
    
    sb.append("    bikeTransport: ").append(toIndentedString(bikeTransport)).append("\n");
    sb.append("    walkSpeed: ").append(toIndentedString(walkSpeed)).append("\n");
    sb.append("    additionalTransferTime: ").append(toIndentedString(additionalTransferTime)).append("\n");
    sb.append("    minimalTransferTime: ").append(toIndentedString(minimalTransferTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
