/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * Trip summary. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class TripSummary {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("summary")
  private String summary = null;

  @JsonProperty("externalRef")
  private String externalRef = null;

  @JsonProperty("startTime")
  private OffsetDateTime startTime = null;

  @JsonProperty("endTime")
  private OffsetDateTime endTime = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("origin")
  private OneOfTripSummaryOrigin origin = null;

  @JsonProperty("destination")
  private OneOfTripSummaryDestination destination = null;

  @JsonProperty("transfers")
  private Integer transfers = null;

  @JsonProperty("distance")
  private Integer distance = null;

  public TripSummary id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of this trip for referencing purposes. Unique within trip response. 
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TripSummary summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public TripSummary externalRef(String externalRef) {
    this.externalRef = externalRef;
    return this;
  }

   /**
   * Get externalRef
   * @return externalRef
  **/
  public String getExternalRef() {
    return externalRef;
  }

  public void setExternalRef(String externalRef) {
    this.externalRef = externalRef;
  }

  public TripSummary startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Departure time at origin. 
   * @return startTime
  **/
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public TripSummary endTime(OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Arrival time at destination. 
   * @return endTime
  **/
  public OffsetDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public TripSummary duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Overall duration of the trip. 
   * @return duration
  **/
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public TripSummary origin(OneOfTripSummaryOrigin origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin
  **/
  public OneOfTripSummaryOrigin getOrigin() {
    return origin;
  }

  public void setOrigin(OneOfTripSummaryOrigin origin) {
    this.origin = origin;
  }

  public TripSummary destination(OneOfTripSummaryDestination destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  public OneOfTripSummaryDestination getDestination() {
    return destination;
  }

  public void setDestination(OneOfTripSummaryDestination destination) {
    this.destination = destination;
  }

  public TripSummary transfers(Integer transfers) {
    this.transfers = transfers;
    return this;
  }

   /**
   * Get transfers
   * @return transfers
  **/
  public Integer getTransfers() {
    return transfers;
  }

  public void setTransfers(Integer transfers) {
    this.transfers = transfers;
  }

  public TripSummary distance(Integer distance) {
    this.distance = distance;
    return this;
  }

   /**
   * Get distance
   * @return distance
  **/
  public Integer getDistance() {
    return distance;
  }

  public void setDistance(Integer distance) {
    this.distance = distance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripSummary tripSummary = (TripSummary) o;
    return Objects.equals(this.id, tripSummary.id) &&
        Objects.equals(this.summary, tripSummary.summary) &&
        Objects.equals(this.externalRef, tripSummary.externalRef) &&
        Objects.equals(this.startTime, tripSummary.startTime) &&
        Objects.equals(this.endTime, tripSummary.endTime) &&
        Objects.equals(this.duration, tripSummary.duration) &&
        Objects.equals(this.origin, tripSummary.origin) &&
        Objects.equals(this.destination, tripSummary.destination) &&
        Objects.equals(this.transfers, tripSummary.transfers) &&
        Objects.equals(this.distance, tripSummary.distance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, summary, externalRef, startTime, endTime, duration, origin, destination, transfers, distance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripSummary {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    externalRef: ").append(toIndentedString(externalRef)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    transfers: ").append(toIndentedString(transfers)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
