/*
 * SBB Swiss Mobility API - Journey
 * ## SBB Swiss Mobility API  <p>This API is one of the modules of the SBB Swiss Mobility API suite (see the <a href=\"https://smapi-cookbooks.app.sbb.ch/cookbooks/smapi-overview/index.html\">SBB Swiss Mobility API Overview</a>). </p> <p>The <strong>SBB Swiss Mobility API - Journey</strong> is a REST API that enables SBB partners to request for <strong>places</strong> and <strong>trips</strong> for swiss public transportation in the OSDM Version 3 standard. </p> <p>Before you request access to the API, please get in contact with <strong>SBB Digital Affiliates</strong>. On the right you can find the contact details. </p> <h3>The OSDM standard</h3> <p>OSDM stands for “Open Sales and Distribution Model”. It aims at simplifying and improving the search and booking of public transportation and to increase interoperability between providers, distributors and retailers. Further details can be found in the official OSDM documentation on osdm.io:</p> <ul>   <li>     <a href=\"https://osdm.io\">OSDM Open Sales and Distribution Model</a>   </li>   <a></a>   <li>     <a href=\"https://github.com/UnionInternationalCheminsdeFer/OSDM\">OSDM Specification</a>   </li>   <li>     <a href=\"https://osdm.io/spec/getting-started/\">Getting Started with OSDM</a>   </li> </ul>
 *
 * OpenAPI spec version: 1.1.4
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.api.smapi.osdm.journey.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.api.smapi.osdm.journey.client.BaseTripPolicyFilter;
import ch.sbb.api.smapi.osdm.journey.client.TripDataFilter;
import ch.sbb.api.smapi.osdm.journey.client.TripMobilityFilter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Options to control the search behavior and response contents. number of results &gt; either number of results or number of results before and after are used. Provided by OJP. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-25T14:33:18.914614100+07:00[Asia/Saigon]")

public class TripParameters {
  @JsonProperty("dataFilter")
  private TripDataFilter dataFilter = null;

  @JsonProperty("policyFilter")
  private BaseTripPolicyFilter policyFilter = null;

  @JsonProperty("mobilityFilter")
  private TripMobilityFilter mobilityFilter = null;

  @JsonProperty("numberOfResults")
  private Integer numberOfResults = null;

  @JsonProperty("numberOfResultsBefore")
  private Integer numberOfResultsBefore = null;

  @JsonProperty("numberOfResultsAfter")
  private Integer numberOfResultsAfter = null;

  @JsonProperty("ignoreRealtimeData")
  private Boolean ignoreRealtimeData = null;

  @JsonProperty("transferLimit")
  private Integer transferLimit = null;

  @JsonProperty("itModesToCover")
  private String itModesToCover = null;

  public TripParameters dataFilter(TripDataFilter dataFilter) {
    this.dataFilter = dataFilter;
    return this;
  }

   /**
   * Get dataFilter
   * @return dataFilter
  **/
  public TripDataFilter getDataFilter() {
    return dataFilter;
  }

  public void setDataFilter(TripDataFilter dataFilter) {
    this.dataFilter = dataFilter;
  }

  public TripParameters policyFilter(BaseTripPolicyFilter policyFilter) {
    this.policyFilter = policyFilter;
    return this;
  }

   /**
   * Get policyFilter
   * @return policyFilter
  **/
  public BaseTripPolicyFilter getPolicyFilter() {
    return policyFilter;
  }

  public void setPolicyFilter(BaseTripPolicyFilter policyFilter) {
    this.policyFilter = policyFilter;
  }

  public TripParameters mobilityFilter(TripMobilityFilter mobilityFilter) {
    this.mobilityFilter = mobilityFilter;
    return this;
  }

   /**
   * Get mobilityFilter
   * @return mobilityFilter
  **/
  public TripMobilityFilter getMobilityFilter() {
    return mobilityFilter;
  }

  public void setMobilityFilter(TripMobilityFilter mobilityFilter) {
    this.mobilityFilter = mobilityFilter;
  }

  public TripParameters numberOfResults(Integer numberOfResults) {
    this.numberOfResults = numberOfResults;
    return this;
  }

   /**
   * Get numberOfResults
   * @return numberOfResults
  **/
  public Integer getNumberOfResults() {
    return numberOfResults;
  }

  public void setNumberOfResults(Integer numberOfResults) {
    this.numberOfResults = numberOfResults;
  }

  public TripParameters numberOfResultsBefore(Integer numberOfResultsBefore) {
    this.numberOfResultsBefore = numberOfResultsBefore;
    return this;
  }

   /**
   * Get numberOfResultsBefore
   * @return numberOfResultsBefore
  **/
  public Integer getNumberOfResultsBefore() {
    return numberOfResultsBefore;
  }

  public void setNumberOfResultsBefore(Integer numberOfResultsBefore) {
    this.numberOfResultsBefore = numberOfResultsBefore;
  }

  public TripParameters numberOfResultsAfter(Integer numberOfResultsAfter) {
    this.numberOfResultsAfter = numberOfResultsAfter;
    return this;
  }

   /**
   * Get numberOfResultsAfter
   * @return numberOfResultsAfter
  **/
  public Integer getNumberOfResultsAfter() {
    return numberOfResultsAfter;
  }

  public void setNumberOfResultsAfter(Integer numberOfResultsAfter) {
    this.numberOfResultsAfter = numberOfResultsAfter;
  }

  public TripParameters ignoreRealtimeData(Boolean ignoreRealtimeData) {
    this.ignoreRealtimeData = ignoreRealtimeData;
    return this;
  }

   /**
   * Get ignoreRealtimeData
   * @return ignoreRealtimeData
  **/
  public Boolean isIgnoreRealtimeData() {
    return ignoreRealtimeData;
  }

  public void setIgnoreRealtimeData(Boolean ignoreRealtimeData) {
    this.ignoreRealtimeData = ignoreRealtimeData;
  }

  public TripParameters transferLimit(Integer transferLimit) {
    this.transferLimit = transferLimit;
    return this;
  }

   /**
   * The maximum number of interchanges the user will accept per trip. 
   * minimum: 0
   * @return transferLimit
  **/
  public Integer getTransferLimit() {
    return transferLimit;
  }

  public void setTransferLimit(Integer transferLimit) {
    this.transferLimit = transferLimit;
  }

  public TripParameters itModesToCover(String itModesToCover) {
    this.itModesToCover = itModesToCover;
    return this;
  }

   /**
   * Modes which an individual powers themselves (such as walk, cycle). Provided by OJP. 
   * @return itModesToCover
  **/
  public String getItModesToCover() {
    return itModesToCover;
  }

  public void setItModesToCover(String itModesToCover) {
    this.itModesToCover = itModesToCover;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripParameters tripParameters = (TripParameters) o;
    return Objects.equals(this.dataFilter, tripParameters.dataFilter) &&
        Objects.equals(this.policyFilter, tripParameters.policyFilter) &&
        Objects.equals(this.mobilityFilter, tripParameters.mobilityFilter) &&
        Objects.equals(this.numberOfResults, tripParameters.numberOfResults) &&
        Objects.equals(this.numberOfResultsBefore, tripParameters.numberOfResultsBefore) &&
        Objects.equals(this.numberOfResultsAfter, tripParameters.numberOfResultsAfter) &&
        Objects.equals(this.ignoreRealtimeData, tripParameters.ignoreRealtimeData) &&
        Objects.equals(this.transferLimit, tripParameters.transferLimit) &&
        Objects.equals(this.itModesToCover, tripParameters.itModesToCover);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataFilter, policyFilter, mobilityFilter, numberOfResults, numberOfResultsBefore, numberOfResultsAfter, ignoreRealtimeData, transferLimit, itModesToCover);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripParameters {\n");
    
    sb.append("    dataFilter: ").append(toIndentedString(dataFilter)).append("\n");
    sb.append("    policyFilter: ").append(toIndentedString(policyFilter)).append("\n");
    sb.append("    mobilityFilter: ").append(toIndentedString(mobilityFilter)).append("\n");
    sb.append("    numberOfResults: ").append(toIndentedString(numberOfResults)).append("\n");
    sb.append("    numberOfResultsBefore: ").append(toIndentedString(numberOfResultsBefore)).append("\n");
    sb.append("    numberOfResultsAfter: ").append(toIndentedString(numberOfResultsAfter)).append("\n");
    sb.append("    ignoreRealtimeData: ").append(toIndentedString(ignoreRealtimeData)).append("\n");
    sb.append("    transferLimit: ").append(toIndentedString(transferLimit)).append("\n");
    sb.append("    itModesToCover: ").append(toIndentedString(itModesToCover)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
