/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * The area that is included in the fare at the end of the trip.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class Area {
  @JsonProperty("areaName")
  private String areaName = null;

  @JsonProperty("areaCode")
  private Integer areaCode = null;

  @JsonProperty("areaLabel")
  private String areaLabel = null;

  @JsonProperty("zoneCodes")
  private List<String> zoneCodes = new ArrayList<>();

  public Area areaName(String areaName) {
    this.areaName = areaName;
    return this;
  }

   /**
   * The name of the Area.
   * @return areaName
  **/
  public String getAreaName() {
    return areaName;
  }

  public void setAreaName(String areaName) {
    this.areaName = areaName;
  }

  public Area areaCode(Integer areaCode) {
    this.areaCode = areaCode;
    return this;
  }

   /**
   * The code of the Area.
   * @return areaCode
  **/
  public Integer getAreaCode() {
    return areaCode;
  }

  public void setAreaCode(Integer areaCode) {
    this.areaCode = areaCode;
  }

  public Area areaLabel(String areaLabel) {
    this.areaLabel = areaLabel;
    return this;
  }

   /**
   * A label for the zones in this area (tariff information).
   * @return areaLabel
  **/
  public String getAreaLabel() {
    return areaLabel;
  }

  public void setAreaLabel(String areaLabel) {
    this.areaLabel = areaLabel;
  }

  public Area zoneCodes(List<String> zoneCodes) {
    this.zoneCodes = zoneCodes;
    return this;
  }

  public Area addZoneCodesItem(String zoneCodesItem) {
    this.zoneCodes.add(zoneCodesItem);
    return this;
  }

   /**
   * Zone codes of the area.
   * @return zoneCodes
  **/
  public List<String> getZoneCodes() {
    return zoneCodes;
  }

  public void setZoneCodes(List<String> zoneCodes) {
    this.zoneCodes = zoneCodes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Area area = (Area) o;
    return Objects.equals(this.areaName, area.areaName) &&
        Objects.equals(this.areaCode, area.areaCode) &&
        Objects.equals(this.areaLabel, area.areaLabel) &&
        Objects.equals(this.zoneCodes, area.zoneCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(areaName, areaCode, areaLabel, zoneCodes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Area {\n");
    
    sb.append("    areaName: ").append(toIndentedString(areaName)).append("\n");
    sb.append("    areaCode: ").append(toIndentedString(areaCode)).append("\n");
    sb.append("    areaLabel: ").append(toIndentedString(areaLabel)).append("\n");
    sb.append("    zoneCodes: ").append(toIndentedString(zoneCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
