/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.ModeOfTransportInformation;
import ch.sbb.app.b2p.client.PassengerInformation;
import ch.sbb.app.b2p.client.TariffInformation;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * A barcode request is made of an original system and id. The tuple original Id / original System is used to identify the leistung in the control system, the values themselves are free text and can be freely determined by the caller. The original system and ID are mandatory, so that the service request may be identified thereafter.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class BarcodeRequest {
  @JsonProperty("originalSystem")
  private String originalSystem = null;

  @JsonProperty("originalId")
  private String originalId = null;

  @JsonProperty("tariffInformation")
  private TariffInformation tariffInformation = null;

  @JsonProperty("passengerInformations")
  private List<PassengerInformation> passengerInformations = null;

  @JsonProperty("additionalInformation")
  private String additionalInformation = null;

  @JsonProperty("modeOfTransportInformations")
  private List<ModeOfTransportInformation> modeOfTransportInformations = null;

  @JsonProperty("specimen")
  private Boolean specimen = null;

  public BarcodeRequest originalSystem(String originalSystem) {
    this.originalSystem = originalSystem;
    return this;
  }

   /**
   * Original system must contain a string identifying the partner.
   * @return originalSystem
  **/
  public String getOriginalSystem() {
    return originalSystem;
  }

  public void setOriginalSystem(String originalSystem) {
    this.originalSystem = originalSystem;
  }

  public BarcodeRequest originalId(String originalId) {
    this.originalId = originalId;
    return this;
  }

   /**
   * Original id must be unique within the space defined by original system.
   * @return originalId
  **/
  public String getOriginalId() {
    return originalId;
  }

  public void setOriginalId(String originalId) {
    this.originalId = originalId;
  }

  public BarcodeRequest tariffInformation(TariffInformation tariffInformation) {
    this.tariffInformation = tariffInformation;
    return this;
  }

   /**
   * Get tariffInformation
   * @return tariffInformation
  **/
  public TariffInformation getTariffInformation() {
    return tariffInformation;
  }

  public void setTariffInformation(TariffInformation tariffInformation) {
    this.tariffInformation = tariffInformation;
  }

  public BarcodeRequest passengerInformations(List<PassengerInformation> passengerInformations) {
    this.passengerInformations = passengerInformations;
    return this;
  }

  public BarcodeRequest addPassengerInformationsItem(PassengerInformation passengerInformationsItem) {
    if (this.passengerInformations == null) {
      this.passengerInformations = new ArrayList<>();
    }
    this.passengerInformations.add(passengerInformationsItem);
    return this;
  }

   /**
   * List of passenger informations
   * @return passengerInformations
  **/
  public List<PassengerInformation> getPassengerInformations() {
    return passengerInformations;
  }

  public void setPassengerInformations(List<PassengerInformation> passengerInformations) {
    this.passengerInformations = passengerInformations;
  }

  public BarcodeRequest additionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
    return this;
  }

   /**
   * Additional Information as freeText on the ticket
   * @return additionalInformation
  **/
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  public BarcodeRequest modeOfTransportInformations(List<ModeOfTransportInformation> modeOfTransportInformations) {
    this.modeOfTransportInformations = modeOfTransportInformations;
    return this;
  }

  public BarcodeRequest addModeOfTransportInformationsItem(ModeOfTransportInformation modeOfTransportInformationsItem) {
    if (this.modeOfTransportInformations == null) {
      this.modeOfTransportInformations = new ArrayList<>();
    }
    this.modeOfTransportInformations.add(modeOfTransportInformationsItem);
    return this;
  }

   /**
   * List of mode of transport informations
   * @return modeOfTransportInformations
  **/
  public List<ModeOfTransportInformation> getModeOfTransportInformations() {
    return modeOfTransportInformations;
  }

  public void setModeOfTransportInformations(List<ModeOfTransportInformation> modeOfTransportInformations) {
    this.modeOfTransportInformations = modeOfTransportInformations;
  }

  public BarcodeRequest specimen(Boolean specimen) {
    this.specimen = specimen;
    return this;
  }

   /**
   * List of mode of transport informations
   * @return specimen
  **/
  public Boolean isSpecimen() {
    return specimen;
  }

  public void setSpecimen(Boolean specimen) {
    this.specimen = specimen;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BarcodeRequest barcodeRequest = (BarcodeRequest) o;
    return Objects.equals(this.originalSystem, barcodeRequest.originalSystem) &&
        Objects.equals(this.originalId, barcodeRequest.originalId) &&
        Objects.equals(this.tariffInformation, barcodeRequest.tariffInformation) &&
        Objects.equals(this.passengerInformations, barcodeRequest.passengerInformations) &&
        Objects.equals(this.additionalInformation, barcodeRequest.additionalInformation) &&
        Objects.equals(this.modeOfTransportInformations, barcodeRequest.modeOfTransportInformations) &&
        Objects.equals(this.specimen, barcodeRequest.specimen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalSystem, originalId, tariffInformation, passengerInformations, additionalInformation, modeOfTransportInformations, specimen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BarcodeRequest {\n");
    
    sb.append("    originalSystem: ").append(toIndentedString(originalSystem)).append("\n");
    sb.append("    originalId: ").append(toIndentedString(originalId)).append("\n");
    sb.append("    tariffInformation: ").append(toIndentedString(tariffInformation)).append("\n");
    sb.append("    passengerInformations: ").append(toIndentedString(passengerInformations)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    modeOfTransportInformations: ").append(toIndentedString(modeOfTransportInformations)).append("\n");
    sb.append("    specimen: ").append(toIndentedString(specimen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
