/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.BookingDataBooking;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Container for the booking data related information.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class BookingResponse {
  @JsonProperty("bookingId")
  private String bookingId = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("bookings")
  private List<BookingDataBooking> bookings = new ArrayList<>();

  public BookingResponse bookingId(String bookingId) {
    this.bookingId = bookingId;
    return this;
  }

   /**
   * Booking id of the booked data items.
   * @return bookingId
  **/
  public String getBookingId() {
    return bookingId;
  }

  public void setBookingId(String bookingId) {
    this.bookingId = bookingId;
  }

  public BookingResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the booking transaction PENDING|COMMITTED.
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public BookingResponse bookings(List<BookingDataBooking> bookings) {
    this.bookings = bookings;
    return this;
  }

  public BookingResponse addBookingsItem(BookingDataBooking bookingsItem) {
    this.bookings.add(bookingsItem);
    return this;
  }

   /**
   * List of booking data items.
   * @return bookings
  **/
  public List<BookingDataBooking> getBookings() {
    return bookings;
  }

  public void setBookings(List<BookingDataBooking> bookings) {
    this.bookings = bookings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingResponse bookingResponse = (BookingResponse) o;
    return Objects.equals(this.bookingId, bookingResponse.bookingId) &&
        Objects.equals(this.status, bookingResponse.status) &&
        Objects.equals(this.bookings, bookingResponse.bookings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingId, status, bookings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookingResponse {\n");
    
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    bookings: ").append(toIndentedString(bookings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
