/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Describes possible travellers and reductions.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class CustomerSegment {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("minAge")
  private Integer minAge = null;

  @JsonProperty("maxAge")
  private Integer maxAge = null;

  /**
   * Type of the traveller.
   */
  public enum TravellerTypeEnum {
    PERSON_DOG_BICYCLE("person, dog, bicycle");

    private String value;

    TravellerTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TravellerTypeEnum fromValue(String input) {
      for (TravellerTypeEnum b : TravellerTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("travellerType")
  private TravellerTypeEnum travellerType = null;

  /**
   * Reduction of the traveller. Possible values: ga-1st, ga-2nd, half-fare, junior-card, child-card, none, swiss-half-fare-card, swiss-travel-pass
   */
  public enum ReductionEnum {
    GA_1ST("ga-1st"),
    GA_2ND("ga-2nd"),
    HALF_FARE("half-fare"),
    JUNIOR_CARD("junior-card"),
    CHILD_CARD("child-card"),
    NONE("none"),
    SWISS_HALF_FARE_CARD("swiss-half-fare-card"),
    SWISS_TRAVEL_PASS("swiss-travel-pass");

    private String value;

    ReductionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ReductionEnum fromValue(String input) {
      for (ReductionEnum b : ReductionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("reduction")
  private ReductionEnum reduction = null;

  public CustomerSegment code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Identifier of the customers segment.
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CustomerSegment title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Human readable title.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public CustomerSegment minAge(Integer minAge) {
    this.minAge = minAge;
    return this;
  }

   /**
   * Minimum age of the traveller.
   * @return minAge
  **/
  public Integer getMinAge() {
    return minAge;
  }

  public void setMinAge(Integer minAge) {
    this.minAge = minAge;
  }

  public CustomerSegment maxAge(Integer maxAge) {
    this.maxAge = maxAge;
    return this;
  }

   /**
   * Maximum age of the traveller.
   * @return maxAge
  **/
  public Integer getMaxAge() {
    return maxAge;
  }

  public void setMaxAge(Integer maxAge) {
    this.maxAge = maxAge;
  }

  public CustomerSegment travellerType(TravellerTypeEnum travellerType) {
    this.travellerType = travellerType;
    return this;
  }

   /**
   * Type of the traveller.
   * @return travellerType
  **/
  public TravellerTypeEnum getTravellerType() {
    return travellerType;
  }

  public void setTravellerType(TravellerTypeEnum travellerType) {
    this.travellerType = travellerType;
  }

  public CustomerSegment reduction(ReductionEnum reduction) {
    this.reduction = reduction;
    return this;
  }

   /**
   * Reduction of the traveller. Possible values: ga-1st, ga-2nd, half-fare, junior-card, child-card, none, swiss-half-fare-card, swiss-travel-pass
   * @return reduction
  **/
  public ReductionEnum getReduction() {
    return reduction;
  }

  public void setReduction(ReductionEnum reduction) {
    this.reduction = reduction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerSegment customerSegment = (CustomerSegment) o;
    return Objects.equals(this.code, customerSegment.code) &&
        Objects.equals(this.title, customerSegment.title) &&
        Objects.equals(this.minAge, customerSegment.minAge) &&
        Objects.equals(this.maxAge, customerSegment.maxAge) &&
        Objects.equals(this.travellerType, customerSegment.travellerType) &&
        Objects.equals(this.reduction, customerSegment.reduction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, title, minAge, maxAge, travellerType, reduction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerSegment {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    minAge: ").append(toIndentedString(minAge)).append("\n");
    sb.append("    maxAge: ").append(toIndentedString(maxAge)).append("\n");
    sb.append("    travellerType: ").append(toIndentedString(travellerType)).append("\n");
    sb.append("    reduction: ").append(toIndentedString(reduction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
