/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EcoBalance: Environmental coefficients to compare train and car transport.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class EcoBalance {
  @JsonProperty("co2Train")
  private Double co2Train = null;

  @JsonProperty("co2Car")
  private Double co2Car = null;

  @JsonProperty("primeTrain")
  private Double primeTrain = null;

  @JsonProperty("primeCar")
  private Double primeCar = null;

  @JsonProperty("durationTrain")
  private String durationTrain = null;

  @JsonProperty("durationCar")
  private String durationCar = null;

  public EcoBalance co2Train(Double co2Train) {
    this.co2Train = co2Train;
    return this;
  }

   /**
   * CO2 emission by train [kg].
   * @return co2Train
  **/
  public Double getCo2Train() {
    return co2Train;
  }

  public void setCo2Train(Double co2Train) {
    this.co2Train = co2Train;
  }

  public EcoBalance co2Car(Double co2Car) {
    this.co2Car = co2Car;
    return this;
  }

   /**
   * CO2 emission by car [kg].
   * @return co2Car
  **/
  public Double getCo2Car() {
    return co2Car;
  }

  public void setCo2Car(Double co2Car) {
    this.co2Car = co2Car;
  }

  public EcoBalance primeTrain(Double primeTrain) {
    this.primeTrain = primeTrain;
    return this;
  }

   /**
   * PRIME emission by train, calculated [l petrol].
   * @return primeTrain
  **/
  public Double getPrimeTrain() {
    return primeTrain;
  }

  public void setPrimeTrain(Double primeTrain) {
    this.primeTrain = primeTrain;
  }

  public EcoBalance primeCar(Double primeCar) {
    this.primeCar = primeCar;
    return this;
  }

   /**
   * PRIME emission by car, calculated [l petrol].
   * @return primeCar
  **/
  public Double getPrimeCar() {
    return primeCar;
  }

  public void setPrimeCar(Double primeCar) {
    this.primeCar = primeCar;
  }

  public EcoBalance durationTrain(String durationTrain) {
    this.durationTrain = durationTrain;
    return this;
  }

   /**
   * Travelling time by train (see [duration](https://www.w3.org/TR/xmlschema11-2/#duration)).
   * @return durationTrain
  **/
  public String getDurationTrain() {
    return durationTrain;
  }

  public void setDurationTrain(String durationTrain) {
    this.durationTrain = durationTrain;
  }

  public EcoBalance durationCar(String durationCar) {
    this.durationCar = durationCar;
    return this;
  }

   /**
   * Travelling time by car (see [duration](https://www.w3.org/TR/xmlschema11-2/#duration)).
   * @return durationCar
  **/
  public String getDurationCar() {
    return durationCar;
  }

  public void setDurationCar(String durationCar) {
    this.durationCar = durationCar;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EcoBalance ecoBalance = (EcoBalance) o;
    return Objects.equals(this.co2Train, ecoBalance.co2Train) &&
        Objects.equals(this.co2Car, ecoBalance.co2Car) &&
        Objects.equals(this.primeTrain, ecoBalance.primeTrain) &&
        Objects.equals(this.primeCar, ecoBalance.primeCar) &&
        Objects.equals(this.durationTrain, ecoBalance.durationTrain) &&
        Objects.equals(this.durationCar, ecoBalance.durationCar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(co2Train, co2Car, primeTrain, primeCar, durationTrain, durationCar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EcoBalance {\n");
    
    sb.append("    co2Train: ").append(toIndentedString(co2Train)).append("\n");
    sb.append("    co2Car: ").append(toIndentedString(co2Car)).append("\n");
    sb.append("    primeTrain: ").append(toIndentedString(primeTrain)).append("\n");
    sb.append("    primeCar: ").append(toIndentedString(primeCar)).append("\n");
    sb.append("    durationTrain: ").append(toIndentedString(durationTrain)).append("\n");
    sb.append("    durationCar: ").append(toIndentedString(durationCar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
