/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Provider of descriptions in different languages.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class LocalizedDescription {
  @JsonProperty("de")
  private String de = null;

  @JsonProperty("en")
  private String en = null;

  @JsonProperty("fr")
  private String fr = null;

  @JsonProperty("it")
  private String it = null;

  public LocalizedDescription de(String de) {
    this.de = de;
    return this;
  }

   /**
   * Description in German
   * @return de
  **/
  public String getDe() {
    return de;
  }

  public void setDe(String de) {
    this.de = de;
  }

  public LocalizedDescription en(String en) {
    this.en = en;
    return this;
  }

   /**
   * Description in English
   * @return en
  **/
  public String getEn() {
    return en;
  }

  public void setEn(String en) {
    this.en = en;
  }

  public LocalizedDescription fr(String fr) {
    this.fr = fr;
    return this;
  }

   /**
   * Description in French
   * @return fr
  **/
  public String getFr() {
    return fr;
  }

  public void setFr(String fr) {
    this.fr = fr;
  }

  public LocalizedDescription it(String it) {
    this.it = it;
    return this;
  }

   /**
   * Description in Italian
   * @return it
  **/
  public String getIt() {
    return it;
  }

  public void setIt(String it) {
    this.it = it;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalizedDescription localizedDescription = (LocalizedDescription) o;
    return Objects.equals(this.de, localizedDescription.de) &&
        Objects.equals(this.en, localizedDescription.en) &&
        Objects.equals(this.fr, localizedDescription.fr) &&
        Objects.equals(this.it, localizedDescription.it);
  }

  @Override
  public int hashCode() {
    return Objects.hash(de, en, fr, it);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalizedDescription {\n");
    
    sb.append("    de: ").append(toIndentedString(de)).append("\n");
    sb.append("    en: ").append(toIndentedString(en)).append("\n");
    sb.append("    fr: ").append(toIndentedString(fr)).append("\n");
    sb.append("    it: ").append(toIndentedString(it)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
