/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.CoordinatesWGS84;
import ch.sbb.app.b2p.client.Link;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * A STATION with its characteristics (aka J-S v3 StopPlace).
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class Location {
  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("coordinates")
  private CoordinatesWGS84 coordinates = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("tariffBorder")
  private Boolean tariffBorder = null;

  @JsonProperty("weight")
  private Integer weight = null;

  /**
   * Type of vehicle of the transport-product.
   */
  public enum VehicleTypesEnum {
    BOAT("BOAT"),
    BUS("BUS"),
    CABLE("CABLE"),
    METRO("METRO"),
    TRAIN("TRAIN"),
    TRAMWAY("TRAMWAY"),
    CHAIRLIFT("CHAIRLIFT"),
    COG_RAILWAY("COG_RAILWAY"),
    TAXI("TAXI"),
    LIFT("LIFT"),
    AIRPLANE("AIRPLANE");

    private String value;

    VehicleTypesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static VehicleTypesEnum fromValue(String input) {
      for (VehicleTypesEnum b : VehicleTypesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("vehicleTypes")
  private List<VehicleTypesEnum> vehicleTypes = null;

  public Location links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Location addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Context information required by the services.
   * @return links
  **/
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public Location id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * UIC code of the location.
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Location name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the location (non-translated resp. name in regional language).
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Location coordinates(CoordinatesWGS84 coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  public CoordinatesWGS84 getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(CoordinatesWGS84 coordinates) {
    this.coordinates = coordinates;
  }

  public Location type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the location.
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Location tariffBorder(Boolean tariffBorder) {
    this.tariffBorder = tariffBorder;
    return this;
  }

   /**
   * NOVA is the public transportation ticketing system in Switzerland and may offer pricing if inside managed NOVA-Zones or not if a trip is extended to international journeys. This flag indicates whether the stop is on the NOVA tariff zone edge or not.
   * @return tariffBorder
  **/
  public Boolean isTariffBorder() {
    return tariffBorder;
  }

  public void setTariffBorder(Boolean tariffBorder) {
    this.tariffBorder = tariffBorder;
  }

  public Location weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Weight (traffic load/importance the higher the value) at station, null if unknown. Example: Zürich HB has weight 30170.
   * @return weight
  **/
  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public Location vehicleTypes(List<VehicleTypesEnum> vehicleTypes) {
    this.vehicleTypes = vehicleTypes;
    return this;
  }

  public Location addVehicleTypesItem(VehicleTypesEnum vehicleTypesItem) {
    if (this.vehicleTypes == null) {
      this.vehicleTypes = new ArrayList<>();
    }
    this.vehicleTypes.add(vehicleTypesItem);
    return this;
  }

   /**
   * List of the vehicle-types supported at this Station. This is a best guess calculated by known planned routes, by means in reality this set might differ.
   * @return vehicleTypes
  **/
  public List<VehicleTypesEnum> getVehicleTypes() {
    return vehicleTypes;
  }

  public void setVehicleTypes(List<VehicleTypesEnum> vehicleTypes) {
    this.vehicleTypes = vehicleTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.links, location.links) &&
        Objects.equals(this.id, location.id) &&
        Objects.equals(this.name, location.name) &&
        Objects.equals(this.coordinates, location.coordinates) &&
        Objects.equals(this.type, location.type) &&
        Objects.equals(this.tariffBorder, location.tariffBorder) &&
        Objects.equals(this.weight, location.weight) &&
        Objects.equals(this.vehicleTypes, location.vehicleTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, id, name, coordinates, type, tariffBorder, weight, vehicleTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tariffBorder: ").append(toIndentedString(tariffBorder)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    vehicleTypes: ").append(toIndentedString(vehicleTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
