/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Information about the Transport Mode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class ModeOfTransportInformation {
  @JsonProperty("courseNumber")
  private String courseNumber = null;

  @JsonProperty("carNumber")
  private String carNumber = null;

  @JsonProperty("placeNumbers")
  private List<String> placeNumbers = null;

  /**
   * Information about the Transport Category
   */
  public enum ModeOfTransportCategoryEnum {
    TRAIN("TRAIN"),
    BUS("BUS"),
    TRAM("TRAM"),
    BOAT("BOAT"),
    CABLERAILWAY("CABLERAILWAY");

    private String value;

    ModeOfTransportCategoryEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ModeOfTransportCategoryEnum fromValue(String input) {
      for (ModeOfTransportCategoryEnum b : ModeOfTransportCategoryEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("modeOfTransportCategory")
  private ModeOfTransportCategoryEnum modeOfTransportCategory = null;

  public ModeOfTransportInformation courseNumber(String courseNumber) {
    this.courseNumber = courseNumber;
    return this;
  }

   /**
   * The number of the course.
   * @return courseNumber
  **/
  public String getCourseNumber() {
    return courseNumber;
  }

  public void setCourseNumber(String courseNumber) {
    this.courseNumber = courseNumber;
  }

  public ModeOfTransportInformation carNumber(String carNumber) {
    this.carNumber = carNumber;
    return this;
  }

   /**
   * The number of the car.
   * @return carNumber
  **/
  public String getCarNumber() {
    return carNumber;
  }

  public void setCarNumber(String carNumber) {
    this.carNumber = carNumber;
  }

  public ModeOfTransportInformation placeNumbers(List<String> placeNumbers) {
    this.placeNumbers = placeNumbers;
    return this;
  }

  public ModeOfTransportInformation addPlaceNumbersItem(String placeNumbersItem) {
    if (this.placeNumbers == null) {
      this.placeNumbers = new ArrayList<>();
    }
    this.placeNumbers.add(placeNumbersItem);
    return this;
  }

   /**
   * The number of the place.
   * @return placeNumbers
  **/
  public List<String> getPlaceNumbers() {
    return placeNumbers;
  }

  public void setPlaceNumbers(List<String> placeNumbers) {
    this.placeNumbers = placeNumbers;
  }

  public ModeOfTransportInformation modeOfTransportCategory(ModeOfTransportCategoryEnum modeOfTransportCategory) {
    this.modeOfTransportCategory = modeOfTransportCategory;
    return this;
  }

   /**
   * Information about the Transport Category
   * @return modeOfTransportCategory
  **/
  public ModeOfTransportCategoryEnum getModeOfTransportCategory() {
    return modeOfTransportCategory;
  }

  public void setModeOfTransportCategory(ModeOfTransportCategoryEnum modeOfTransportCategory) {
    this.modeOfTransportCategory = modeOfTransportCategory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModeOfTransportInformation modeOfTransportInformation = (ModeOfTransportInformation) o;
    return Objects.equals(this.courseNumber, modeOfTransportInformation.courseNumber) &&
        Objects.equals(this.carNumber, modeOfTransportInformation.carNumber) &&
        Objects.equals(this.placeNumbers, modeOfTransportInformation.placeNumbers) &&
        Objects.equals(this.modeOfTransportCategory, modeOfTransportInformation.modeOfTransportCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(courseNumber, carNumber, placeNumbers, modeOfTransportCategory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModeOfTransportInformation {\n");
    
    sb.append("    courseNumber: ").append(toIndentedString(courseNumber)).append("\n");
    sb.append("    carNumber: ").append(toIndentedString(carNumber)).append("\n");
    sb.append("    placeNumbers: ").append(toIndentedString(placeNumbers)).append("\n");
    sb.append("    modeOfTransportCategory: ").append(toIndentedString(modeOfTransportCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
