/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Attachable attribute (tag) contents.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class Note {
  @JsonProperty("key")
  private String key = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("routeIndexFrom")
  private Integer routeIndexFrom = null;

  @JsonProperty("routeIndexTo")
  private Integer routeIndexTo = null;

  public Note key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Key given by SBB Data-Management.
   * @return key
  **/
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Note value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Speaking, translatable text related to key.
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Note priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * A lower priority value means a higher importance (default&#x3D;100).
   * @return priority
  **/
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public Note routeIndexFrom(Integer routeIndexFrom) {
    this.routeIndexFrom = routeIndexFrom;
    return this;
  }

   /**
   * Relates to Stop::routeIndex where this note is valid from.
   * @return routeIndexFrom
  **/
  public Integer getRouteIndexFrom() {
    return routeIndexFrom;
  }

  public void setRouteIndexFrom(Integer routeIndexFrom) {
    this.routeIndexFrom = routeIndexFrom;
  }

  public Note routeIndexTo(Integer routeIndexTo) {
    this.routeIndexTo = routeIndexTo;
    return this;
  }

   /**
   * Relates to Stop::routeIndex where this note is valid to.
   * @return routeIndexTo
  **/
  public Integer getRouteIndexTo() {
    return routeIndexTo;
  }

  public void setRouteIndexTo(Integer routeIndexTo) {
    this.routeIndexTo = routeIndexTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Note note = (Note) o;
    return Objects.equals(this.key, note.key) &&
        Objects.equals(this.value, note.value) &&
        Objects.equals(this.priority, note.priority) &&
        Objects.equals(this.routeIndexFrom, note.routeIndexFrom) &&
        Objects.equals(this.routeIndexTo, note.routeIndexTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value, priority, routeIndexFrom, routeIndexTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Note {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    routeIndexFrom: ").append(toIndentedString(routeIndexFrom)).append("\n");
    sb.append("    routeIndexTo: ").append(toIndentedString(routeIndexTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
