/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.Link;
import ch.sbb.app.b2p.client.Notification;
import ch.sbb.app.b2p.client.Offer;
import ch.sbb.app.b2p.client.OfferCharacteristic;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Contains offers that have to be prebooked together in the prebooking step. The container cannot have mixed 1 and 2 quality of service offers.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class OfferBundle {
  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("totalPrice")
  private Integer totalPrice = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("qualityOfService")
  private Integer qualityOfService = null;

  @JsonProperty("outwardCharacteristic")
  private OfferCharacteristic outwardCharacteristic = null;

  @JsonProperty("returnCharacteristic")
  private OfferCharacteristic returnCharacteristic = null;

  @JsonProperty("offers")
  private List<Offer> offers = new ArrayList<>();

  @JsonProperty("notifications")
  private List<Notification> notifications = null;

  public OfferBundle links(List<Link> links) {
    this.links = links;
    return this;
  }

  public OfferBundle addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Context information required by the services.
   * @return links
  **/
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public OfferBundle totalPrice(Integer totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Total price of all offers in the container
   * @return totalPrice
  **/
  public Integer getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(Integer totalPrice) {
    this.totalPrice = totalPrice;
  }

  public OfferBundle currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency of the total price of all offer items.
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public OfferBundle qualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
    return this;
  }

   /**
   * The quality of service of all offers in the container. 
   * @return qualityOfService
  **/
  public Integer getQualityOfService() {
    return qualityOfService;
  }

  public void setQualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
  }

  public OfferBundle outwardCharacteristic(OfferCharacteristic outwardCharacteristic) {
    this.outwardCharacteristic = outwardCharacteristic;
    return this;
  }

   /**
   * Get outwardCharacteristic
   * @return outwardCharacteristic
  **/
  public OfferCharacteristic getOutwardCharacteristic() {
    return outwardCharacteristic;
  }

  public void setOutwardCharacteristic(OfferCharacteristic outwardCharacteristic) {
    this.outwardCharacteristic = outwardCharacteristic;
  }

  public OfferBundle returnCharacteristic(OfferCharacteristic returnCharacteristic) {
    this.returnCharacteristic = returnCharacteristic;
    return this;
  }

   /**
   * Get returnCharacteristic
   * @return returnCharacteristic
  **/
  public OfferCharacteristic getReturnCharacteristic() {
    return returnCharacteristic;
  }

  public void setReturnCharacteristic(OfferCharacteristic returnCharacteristic) {
    this.returnCharacteristic = returnCharacteristic;
  }

  public OfferBundle offers(List<Offer> offers) {
    this.offers = offers;
    return this;
  }

  public OfferBundle addOffersItem(Offer offersItem) {
    this.offers.add(offersItem);
    return this;
  }

   /**
   * List of offers that have to be prebooked together
   * @return offers
  **/
  public List<Offer> getOffers() {
    return offers;
  }

  public void setOffers(List<Offer> offers) {
    this.offers = offers;
  }

  public OfferBundle notifications(List<Notification> notifications) {
    this.notifications = notifications;
    return this;
  }

  public OfferBundle addNotificationsItem(Notification notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * List of booking relevant notifications
   * @return notifications
  **/
  public List<Notification> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<Notification> notifications) {
    this.notifications = notifications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferBundle offerBundle = (OfferBundle) o;
    return Objects.equals(this.links, offerBundle.links) &&
        Objects.equals(this.totalPrice, offerBundle.totalPrice) &&
        Objects.equals(this.currency, offerBundle.currency) &&
        Objects.equals(this.qualityOfService, offerBundle.qualityOfService) &&
        Objects.equals(this.outwardCharacteristic, offerBundle.outwardCharacteristic) &&
        Objects.equals(this.returnCharacteristic, offerBundle.returnCharacteristic) &&
        Objects.equals(this.offers, offerBundle.offers) &&
        Objects.equals(this.notifications, offerBundle.notifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, totalPrice, currency, qualityOfService, outwardCharacteristic, returnCharacteristic, offers, notifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferBundle {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    qualityOfService: ").append(toIndentedString(qualityOfService)).append("\n");
    sb.append("    outwardCharacteristic: ").append(toIndentedString(outwardCharacteristic)).append("\n");
    sb.append("    returnCharacteristic: ").append(toIndentedString(returnCharacteristic)).append("\n");
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
