/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.PassengerGroupInfo;
import ch.sbb.app.b2p.client.Period;
import ch.sbb.app.b2p.client.RouteValidity;
import ch.sbb.app.b2p.client.SalesParameter;
import ch.sbb.app.b2p.client.TicketPeriod;
import ch.sbb.app.b2p.client.ValidityArea;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * An actual offer for a specific trip with the given characteristics. The fare however is only guaranteed after prebooking.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class Offer {
  @JsonProperty("offerIdentifier")
  private String offerIdentifier = null;

  @JsonProperty("productId")
  private Integer productId = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("offerType")
  private String offerType = null;

  @JsonProperty("passengerId")
  private String passengerId = null;

  @JsonProperty("passengerGroupInfos")
  private List<PassengerGroupInfo> passengerGroupInfos = null;

  @JsonProperty("price")
  private Integer price = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("vat")
  private Integer vat = null;

  @JsonProperty("qualityOfService")
  private Integer qualityOfService = null;

  /**
   * DEPRECATED: The direction of this offer.
   */
  public enum DirectionEnum {
    OUTWARD("outward"),
    RETURN("return"),
    ROUND("round");

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DirectionEnum fromValue(String input) {
      for (DirectionEnum b : DirectionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("direction")
  private DirectionEnum direction = null;

  @JsonProperty("tariffLevel")
  private String tariffLevel = null;

  @JsonProperty("validityArea")
  private ValidityArea validityArea = null;

  @JsonProperty("routeValidity")
  private RouteValidity routeValidity = null;

  @JsonProperty("offerValidity")
  private Period offerValidity = null;

  @JsonProperty("ticketValidity")
  private TicketPeriod ticketValidity = null;

  @JsonProperty("salesParameter")
  private List<SalesParameter> salesParameter = null;

  @JsonProperty("refundable")
  private Boolean refundable = null;

  @JsonProperty("exchangeable")
  private Boolean exchangeable = null;

  @JsonProperty("requiresPurchase")
  private Boolean requiresPurchase = null;

  public Offer offerIdentifier(String offerIdentifier) {
    this.offerIdentifier = offerIdentifier;
    return this;
  }

   /**
   * ID of the current offer that can be used for prebooking.
   * @return offerIdentifier
  **/
  public String getOfferIdentifier() {
    return offerIdentifier;
  }

  public void setOfferIdentifier(String offerIdentifier) {
    this.offerIdentifier = offerIdentifier;
  }

  public Offer productId(Integer productId) {
    this.productId = productId;
    return this;
  }

   /**
   * ID of the product that the offer is based on.
   * @return productId
  **/
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  public Offer title(String title) {
    this.title = title;
    return this;
  }

   /**
   * A short title that describes what the offer is for.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Offer description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A short description of the offer with characteristics and rules that may apply.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Offer offerType(String offerType) {
    this.offerType = offerType;
    return this;
  }

   /**
   * The offer type, one of TRANSPORT, TRANSPORT_WITH_SEAT_RESERVATION, SEAT_RESERVATION, CLASS_UPGRADE.
   * @return offerType
  **/
  public String getOfferType() {
    return offerType;
  }

  public void setOfferType(String offerType) {
    this.offerType = offerType;
  }

  public Offer passengerId(String passengerId) {
    this.passengerId = passengerId;
    return this;
  }

   /**
   * The id of the passenger for which the offer was created. Unset for group trip requests.
   * @return passengerId
  **/
  public String getPassengerId() {
    return passengerId;
  }

  public void setPassengerId(String passengerId) {
    this.passengerId = passengerId;
  }

  public Offer passengerGroupInfos(List<PassengerGroupInfo> passengerGroupInfos) {
    this.passengerGroupInfos = passengerGroupInfos;
    return this;
  }

  public Offer addPassengerGroupInfosItem(PassengerGroupInfo passengerGroupInfosItem) {
    if (this.passengerGroupInfos == null) {
      this.passengerGroupInfos = new ArrayList<>();
    }
    this.passengerGroupInfos.add(passengerGroupInfosItem);
    return this;
  }

   /**
   * Detailed information for the groups of passengers of a group trip. Unset for regular trip requests.
   * @return passengerGroupInfos
  **/
  public List<PassengerGroupInfo> getPassengerGroupInfos() {
    return passengerGroupInfos;
  }

  public void setPassengerGroupInfos(List<PassengerGroupInfo> passengerGroupInfos) {
    this.passengerGroupInfos = passengerGroupInfos;
  }

  public Offer price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * Price of the current offer with the given characteristics.
   * @return price
  **/
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public Offer currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency of the given price of the offer.
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Offer vat(Integer vat) {
    this.vat = vat;
    return this;
  }

   /**
   * VAT percentage used to calculate the price (per mille - ‰) (7.7% -&gt; 77).
   * @return vat
  **/
  public Integer getVat() {
    return vat;
  }

  public void setVat(Integer vat) {
    this.vat = vat;
  }

  public Offer qualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
    return this;
  }

   /**
   * The quality of service for this offer.
   * @return qualityOfService
  **/
  public Integer getQualityOfService() {
    return qualityOfService;
  }

  public void setQualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
  }

  public Offer direction(DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

   /**
   * DEPRECATED: The direction of this offer.
   * @return direction
  **/
  public DirectionEnum getDirection() {
    return direction;
  }

  public void setDirection(DirectionEnum direction) {
    this.direction = direction;
  }

  public Offer tariffLevel(String tariffLevel) {
    this.tariffLevel = tariffLevel;
    return this;
  }

   /**
   * A text description of the current tariff level.
   * @return tariffLevel
  **/
  public String getTariffLevel() {
    return tariffLevel;
  }

  public void setTariffLevel(String tariffLevel) {
    this.tariffLevel = tariffLevel;
  }

  public Offer validityArea(ValidityArea validityArea) {
    this.validityArea = validityArea;
    return this;
  }

   /**
   * Get validityArea
   * @return validityArea
  **/
  public ValidityArea getValidityArea() {
    return validityArea;
  }

  public void setValidityArea(ValidityArea validityArea) {
    this.validityArea = validityArea;
  }

  public Offer routeValidity(RouteValidity routeValidity) {
    this.routeValidity = routeValidity;
    return this;
  }

   /**
   * Get routeValidity
   * @return routeValidity
  **/
  public RouteValidity getRouteValidity() {
    return routeValidity;
  }

  public void setRouteValidity(RouteValidity routeValidity) {
    this.routeValidity = routeValidity;
  }

  public Offer offerValidity(Period offerValidity) {
    this.offerValidity = offerValidity;
    return this;
  }

   /**
   * Get offerValidity
   * @return offerValidity
  **/
  public Period getOfferValidity() {
    return offerValidity;
  }

  public void setOfferValidity(Period offerValidity) {
    this.offerValidity = offerValidity;
  }

  public Offer ticketValidity(TicketPeriod ticketValidity) {
    this.ticketValidity = ticketValidity;
    return this;
  }

   /**
   * Get ticketValidity
   * @return ticketValidity
  **/
  public TicketPeriod getTicketValidity() {
    return ticketValidity;
  }

  public void setTicketValidity(TicketPeriod ticketValidity) {
    this.ticketValidity = ticketValidity;
  }

  public Offer salesParameter(List<SalesParameter> salesParameter) {
    this.salesParameter = salesParameter;
    return this;
  }

  public Offer addSalesParameterItem(SalesParameter salesParameterItem) {
    if (this.salesParameter == null) {
      this.salesParameter = new ArrayList<>();
    }
    this.salesParameter.add(salesParameterItem);
    return this;
  }

   /**
   * The applicable parameters to prebook this offer.
   * @return salesParameter
  **/
  public List<SalesParameter> getSalesParameter() {
    return salesParameter;
  }

  public void setSalesParameter(List<SalesParameter> salesParameter) {
    this.salesParameter = salesParameter;
  }

  public Offer refundable(Boolean refundable) {
    this.refundable = refundable;
    return this;
  }

   /**
   * Indicates whether the offered ticket/product is refundable or not.
   * @return refundable
  **/
  public Boolean isRefundable() {
    return refundable;
  }

  public void setRefundable(Boolean refundable) {
    this.refundable = refundable;
  }

  public Offer exchangeable(Boolean exchangeable) {
    this.exchangeable = exchangeable;
    return this;
  }

   /**
   * Indicates whether the offered ticket/product is exchangeable or not.
   * @return exchangeable
  **/
  public Boolean isExchangeable() {
    return exchangeable;
  }

  public void setExchangeable(Boolean exchangeable) {
    this.exchangeable = exchangeable;
  }

  public Offer requiresPurchase(Boolean requiresPurchase) {
    this.requiresPurchase = requiresPurchase;
    return this;
  }

   /**
   * Indicates whether the offer needs to be bought or not.
   * @return requiresPurchase
  **/
  public Boolean isRequiresPurchase() {
    return requiresPurchase;
  }

  public void setRequiresPurchase(Boolean requiresPurchase) {
    this.requiresPurchase = requiresPurchase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Offer offer = (Offer) o;
    return Objects.equals(this.offerIdentifier, offer.offerIdentifier) &&
        Objects.equals(this.productId, offer.productId) &&
        Objects.equals(this.title, offer.title) &&
        Objects.equals(this.description, offer.description) &&
        Objects.equals(this.offerType, offer.offerType) &&
        Objects.equals(this.passengerId, offer.passengerId) &&
        Objects.equals(this.passengerGroupInfos, offer.passengerGroupInfos) &&
        Objects.equals(this.price, offer.price) &&
        Objects.equals(this.currency, offer.currency) &&
        Objects.equals(this.vat, offer.vat) &&
        Objects.equals(this.qualityOfService, offer.qualityOfService) &&
        Objects.equals(this.direction, offer.direction) &&
        Objects.equals(this.tariffLevel, offer.tariffLevel) &&
        Objects.equals(this.validityArea, offer.validityArea) &&
        Objects.equals(this.routeValidity, offer.routeValidity) &&
        Objects.equals(this.offerValidity, offer.offerValidity) &&
        Objects.equals(this.ticketValidity, offer.ticketValidity) &&
        Objects.equals(this.salesParameter, offer.salesParameter) &&
        Objects.equals(this.refundable, offer.refundable) &&
        Objects.equals(this.exchangeable, offer.exchangeable) &&
        Objects.equals(this.requiresPurchase, offer.requiresPurchase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerIdentifier, productId, title, description, offerType, passengerId, passengerGroupInfos, price, currency, vat, qualityOfService, direction, tariffLevel, validityArea, routeValidity, offerValidity, ticketValidity, salesParameter, refundable, exchangeable, requiresPurchase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Offer {\n");
    
    sb.append("    offerIdentifier: ").append(toIndentedString(offerIdentifier)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    offerType: ").append(toIndentedString(offerType)).append("\n");
    sb.append("    passengerId: ").append(toIndentedString(passengerId)).append("\n");
    sb.append("    passengerGroupInfos: ").append(toIndentedString(passengerGroupInfos)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    vat: ").append(toIndentedString(vat)).append("\n");
    sb.append("    qualityOfService: ").append(toIndentedString(qualityOfService)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    tariffLevel: ").append(toIndentedString(tariffLevel)).append("\n");
    sb.append("    validityArea: ").append(toIndentedString(validityArea)).append("\n");
    sb.append("    routeValidity: ").append(toIndentedString(routeValidity)).append("\n");
    sb.append("    offerValidity: ").append(toIndentedString(offerValidity)).append("\n");
    sb.append("    ticketValidity: ").append(toIndentedString(ticketValidity)).append("\n");
    sb.append("    salesParameter: ").append(toIndentedString(salesParameter)).append("\n");
    sb.append("    refundable: ").append(toIndentedString(refundable)).append("\n");
    sb.append("    exchangeable: ").append(toIndentedString(exchangeable)).append("\n");
    sb.append("    requiresPurchase: ").append(toIndentedString(requiresPurchase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
