/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.OfferPrebookRequest;
import ch.sbb.app.b2p.client.PrebookingBikeV2;
import ch.sbb.app.b2p.client.PrebookingDogV2;
import ch.sbb.app.b2p.client.PrebookingPassengerV2;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * The prebooking request.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class PrebookRequestV2 {
  @JsonProperty("offerPrebookings")
  private List<OfferPrebookRequest> offerPrebookings = null;

  @JsonProperty("passenger")
  private PrebookingPassengerV2 passenger = null;

  @JsonProperty("dog")
  private PrebookingDogV2 dog = null;

  @JsonProperty("bike")
  private PrebookingBikeV2 bike = null;

  public PrebookRequestV2 offerPrebookings(List<OfferPrebookRequest> offerPrebookings) {
    this.offerPrebookings = offerPrebookings;
    return this;
  }

  public PrebookRequestV2 addOfferPrebookingsItem(OfferPrebookRequest offerPrebookingsItem) {
    if (this.offerPrebookings == null) {
      this.offerPrebookings = new ArrayList<>();
    }
    this.offerPrebookings.add(offerPrebookingsItem);
    return this;
  }

   /**
   * Prebook requests for offers.
   * @return offerPrebookings
  **/
  public List<OfferPrebookRequest> getOfferPrebookings() {
    return offerPrebookings;
  }

  public void setOfferPrebookings(List<OfferPrebookRequest> offerPrebookings) {
    this.offerPrebookings = offerPrebookings;
  }

  public PrebookRequestV2 passenger(PrebookingPassengerV2 passenger) {
    this.passenger = passenger;
    return this;
  }

   /**
   * Get passenger
   * @return passenger
  **/
  public PrebookingPassengerV2 getPassenger() {
    return passenger;
  }

  public void setPassenger(PrebookingPassengerV2 passenger) {
    this.passenger = passenger;
  }

  public PrebookRequestV2 dog(PrebookingDogV2 dog) {
    this.dog = dog;
    return this;
  }

   /**
   * Get dog
   * @return dog
  **/
  public PrebookingDogV2 getDog() {
    return dog;
  }

  public void setDog(PrebookingDogV2 dog) {
    this.dog = dog;
  }

  public PrebookRequestV2 bike(PrebookingBikeV2 bike) {
    this.bike = bike;
    return this;
  }

   /**
   * Get bike
   * @return bike
  **/
  public PrebookingBikeV2 getBike() {
    return bike;
  }

  public void setBike(PrebookingBikeV2 bike) {
    this.bike = bike;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrebookRequestV2 prebookRequestV2 = (PrebookRequestV2) o;
    return Objects.equals(this.offerPrebookings, prebookRequestV2.offerPrebookings) &&
        Objects.equals(this.passenger, prebookRequestV2.passenger) &&
        Objects.equals(this.dog, prebookRequestV2.dog) &&
        Objects.equals(this.bike, prebookRequestV2.bike);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerPrebookings, passenger, dog, bike);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrebookRequestV2 {\n");
    
    sb.append("    offerPrebookings: ").append(toIndentedString(offerPrebookings)).append("\n");
    sb.append("    passenger: ").append(toIndentedString(passenger)).append("\n");
    sb.append("    dog: ").append(toIndentedString(dog)).append("\n");
    sb.append("    bike: ").append(toIndentedString(bike)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
