/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * The prices request.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class PricesRequest {
  /**
   * Passenger data required to request an offer. Consists of the passenger id, the age of the passenger and the type of reduction card separated by a semicolon. Supported reduction codes are: {ga-1st, ga-2nd, half-fare, junior-card, child-card, none, swiss-half-fare-card, swiss-travel-pass}.
   */
  public enum PassengersEnum {
    GA_1ST("ga-1st"),
    GA_2ND("ga-2nd"),
    HALF_FARE("half-fare"),
    JUNIOR_CARD("junior-card"),
    CHILD_CARD("child-card"),
    NONE("none"),
    SWISS_HALF_FARE_CARD("swiss-half-fare-card"),
    SWISS_TRAVEL_PASS("swiss-travel-pass");

    private String value;

    PassengersEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PassengersEnum fromValue(String input) {
      for (PassengersEnum b : PassengersEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("passengers")
  private List<PassengersEnum> passengers = new ArrayList<>();

  @JsonProperty("qualityOfService")
  private Integer qualityOfService = null;

  @JsonProperty("tripIds")
  private List<String> tripIds = new ArrayList<>();

  @JsonProperty("productId")
  private Long productId = null;

  public PricesRequest passengers(List<PassengersEnum> passengers) {
    this.passengers = passengers;
    return this;
  }

  public PricesRequest addPassengersItem(PassengersEnum passengersItem) {
    this.passengers.add(passengersItem);
    return this;
  }

   /**
   * An array of passengers each of which contains id, age and reduction separated by a semicolon. (Can be multiple)
   * @return passengers
  **/
  public List<PassengersEnum> getPassengers() {
    return passengers;
  }

  public void setPassengers(List<PassengersEnum> passengers) {
    this.passengers = passengers;
  }

  public PricesRequest qualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
    return this;
  }

   /**
   * The quality of service of the travel: 1, 2.
   * @return qualityOfService
  **/
  public Integer getQualityOfService() {
    return qualityOfService;
  }

  public void setQualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
  }

  public PricesRequest tripIds(List<String> tripIds) {
    this.tripIds = tripIds;
    return this;
  }

  public PricesRequest addTripIdsItem(String tripIdsItem) {
    this.tripIds.add(tripIdsItem);
    return this;
  }

   /**
   * The tripId for this journey. It is the Base64 encoded HAFAS reconstruction context. The tripId can also be retrieved with the trips service.
   * @return tripIds
  **/
  public List<String> getTripIds() {
    return tripIds;
  }

  public void setTripIds(List<String> tripIds) {
    this.tripIds = tripIds;
  }

  public PricesRequest productId(Long productId) {
    this.productId = productId;
    return this;
  }

   /**
   * The desired product id for the prices.
   * @return productId
  **/
  public Long getProductId() {
    return productId;
  }

  public void setProductId(Long productId) {
    this.productId = productId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricesRequest pricesRequest = (PricesRequest) o;
    return Objects.equals(this.passengers, pricesRequest.passengers) &&
        Objects.equals(this.qualityOfService, pricesRequest.qualityOfService) &&
        Objects.equals(this.tripIds, pricesRequest.tripIds) &&
        Objects.equals(this.productId, pricesRequest.productId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengers, qualityOfService, tripIds, productId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricesRequest {\n");
    
    sb.append("    passengers: ").append(toIndentedString(passengers)).append("\n");
    sb.append("    qualityOfService: ").append(toIndentedString(qualityOfService)).append("\n");
    sb.append("    tripIds: ").append(toIndentedString(tripIds)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
