/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.CustomerSegment;
import ch.sbb.app.b2p.client.Link;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
/**
 * A product with it characteristics.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class Product {
  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("qualityOfService")
  private List<Integer> qualityOfService = new ArrayList<>();

  @JsonProperty("sellableFrom")
  private LocalDate sellableFrom = null;

  @JsonProperty("sellableUntil")
  private LocalDate sellableUntil = null;

  @JsonProperty("usefulLifeFrom")
  private LocalDate usefulLifeFrom = null;

  @JsonProperty("usefulLifeUntil")
  private LocalDate usefulLifeUntil = null;

  @JsonProperty("validFrom")
  private LocalDate validFrom = null;

  @JsonProperty("validTo")
  private LocalDate validTo = null;

  @JsonProperty("offerEndpoints")
  private List<String> offerEndpoints = new ArrayList<>();

  @JsonProperty("customerSegments")
  private List<CustomerSegment> customerSegments = new ArrayList<>();

  public Product links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Product addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Context information required by the services.
   * @return links
  **/
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public Product id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The product definition identifier.
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Product description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the current product.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Product qualityOfService(List<Integer> qualityOfService) {
    this.qualityOfService = qualityOfService;
    return this;
  }

  public Product addQualityOfServiceItem(Integer qualityOfServiceItem) {
    this.qualityOfService.add(qualityOfServiceItem);
    return this;
  }

   /**
   * Available quality of service.
   * @return qualityOfService
  **/
  public List<Integer> getQualityOfService() {
    return qualityOfService;
  }

  public void setQualityOfService(List<Integer> qualityOfService) {
    this.qualityOfService = qualityOfService;
  }

  public Product sellableFrom(LocalDate sellableFrom) {
    this.sellableFrom = sellableFrom;
    return this;
  }

   /**
   * First day of saleability.
   * @return sellableFrom
  **/
  public LocalDate getSellableFrom() {
    return sellableFrom;
  }

  public void setSellableFrom(LocalDate sellableFrom) {
    this.sellableFrom = sellableFrom;
  }

  public Product sellableUntil(LocalDate sellableUntil) {
    this.sellableUntil = sellableUntil;
    return this;
  }

   /**
   * Last day of saleability.
   * @return sellableUntil
  **/
  public LocalDate getSellableUntil() {
    return sellableUntil;
  }

  public void setSellableUntil(LocalDate sellableUntil) {
    this.sellableUntil = sellableUntil;
  }

  public Product usefulLifeFrom(LocalDate usefulLifeFrom) {
    this.usefulLifeFrom = usefulLifeFrom;
    return this;
  }

   /**
   * Fist day of useful life.
   * @return usefulLifeFrom
  **/
  public LocalDate getUsefulLifeFrom() {
    return usefulLifeFrom;
  }

  public void setUsefulLifeFrom(LocalDate usefulLifeFrom) {
    this.usefulLifeFrom = usefulLifeFrom;
  }

  public Product usefulLifeUntil(LocalDate usefulLifeUntil) {
    this.usefulLifeUntil = usefulLifeUntil;
    return this;
  }

   /**
   * Last day of useful life.
   * @return usefulLifeUntil
  **/
  public LocalDate getUsefulLifeUntil() {
    return usefulLifeUntil;
  }

  public void setUsefulLifeUntil(LocalDate usefulLifeUntil) {
    this.usefulLifeUntil = usefulLifeUntil;
  }

  public Product validFrom(LocalDate validFrom) {
    this.validFrom = validFrom;
    return this;
  }

   /**
   * First day of validity.
   * @return validFrom
  **/
  public LocalDate getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(LocalDate validFrom) {
    this.validFrom = validFrom;
  }

  public Product validTo(LocalDate validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * Last day of validity.
   * @return validTo
  **/
  public LocalDate getValidTo() {
    return validTo;
  }

  public void setValidTo(LocalDate validTo) {
    this.validTo = validTo;
  }

  public Product offerEndpoints(List<String> offerEndpoints) {
    this.offerEndpoints = offerEndpoints;
    return this;
  }

  public Product addOfferEndpointsItem(String offerEndpointsItem) {
    this.offerEndpoints.add(offerEndpointsItem);
    return this;
  }

   /**
   * Possible offer endpoints. Allowed values: trip, route, product
   * @return offerEndpoints
  **/
  public List<String> getOfferEndpoints() {
    return offerEndpoints;
  }

  public void setOfferEndpoints(List<String> offerEndpoints) {
    this.offerEndpoints = offerEndpoints;
  }

  public Product customerSegments(List<CustomerSegment> customerSegments) {
    this.customerSegments = customerSegments;
    return this;
  }

  public Product addCustomerSegmentsItem(CustomerSegment customerSegmentsItem) {
    this.customerSegments.add(customerSegmentsItem);
    return this;
  }

   /**
   * Possible customer segments.
   * @return customerSegments
  **/
  public List<CustomerSegment> getCustomerSegments() {
    return customerSegments;
  }

  public void setCustomerSegments(List<CustomerSegment> customerSegments) {
    this.customerSegments = customerSegments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.links, product.links) &&
        Objects.equals(this.id, product.id) &&
        Objects.equals(this.description, product.description) &&
        Objects.equals(this.qualityOfService, product.qualityOfService) &&
        Objects.equals(this.sellableFrom, product.sellableFrom) &&
        Objects.equals(this.sellableUntil, product.sellableUntil) &&
        Objects.equals(this.usefulLifeFrom, product.usefulLifeFrom) &&
        Objects.equals(this.usefulLifeUntil, product.usefulLifeUntil) &&
        Objects.equals(this.validFrom, product.validFrom) &&
        Objects.equals(this.validTo, product.validTo) &&
        Objects.equals(this.offerEndpoints, product.offerEndpoints) &&
        Objects.equals(this.customerSegments, product.customerSegments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, id, description, qualityOfService, sellableFrom, sellableUntil, usefulLifeFrom, usefulLifeUntil, validFrom, validTo, offerEndpoints, customerSegments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    qualityOfService: ").append(toIndentedString(qualityOfService)).append("\n");
    sb.append("    sellableFrom: ").append(toIndentedString(sellableFrom)).append("\n");
    sb.append("    sellableUntil: ").append(toIndentedString(sellableUntil)).append("\n");
    sb.append("    usefulLifeFrom: ").append(toIndentedString(usefulLifeFrom)).append("\n");
    sb.append("    usefulLifeUntil: ").append(toIndentedString(usefulLifeUntil)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    offerEndpoints: ").append(toIndentedString(offerEndpoints)).append("\n");
    sb.append("    customerSegments: ").append(toIndentedString(customerSegments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
