/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.RefundReason;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Data related to the refund of the booking item.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class RefundData {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("onlyIndividuallyRefundable")
  private Boolean onlyIndividuallyRefundable = null;

  @JsonProperty("refundReasons")
  private List<RefundReason> refundReasons = new ArrayList<>();

  public RefundData type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the refund, e.g. whether it is a full refund.
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RefundData onlyIndividuallyRefundable(Boolean onlyIndividuallyRefundable) {
    this.onlyIndividuallyRefundable = onlyIndividuallyRefundable;
    return this;
  }

   /**
   * Indicates whether the booked item is only individually refundable or not.
   * @return onlyIndividuallyRefundable
  **/
  public Boolean isOnlyIndividuallyRefundable() {
    return onlyIndividuallyRefundable;
  }

  public void setOnlyIndividuallyRefundable(Boolean onlyIndividuallyRefundable) {
    this.onlyIndividuallyRefundable = onlyIndividuallyRefundable;
  }

  public RefundData refundReasons(List<RefundReason> refundReasons) {
    this.refundReasons = refundReasons;
    return this;
  }

  public RefundData addRefundReasonsItem(RefundReason refundReasonsItem) {
    this.refundReasons.add(refundReasonsItem);
    return this;
  }

   /**
   * List of refund reasons supported to do the refund of the booked item.
   * @return refundReasons
  **/
  public List<RefundReason> getRefundReasons() {
    return refundReasons;
  }

  public void setRefundReasons(List<RefundReason> refundReasons) {
    this.refundReasons = refundReasons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundData refundData = (RefundData) o;
    return Objects.equals(this.type, refundData.type) &&
        Objects.equals(this.onlyIndividuallyRefundable, refundData.onlyIndividuallyRefundable) &&
        Objects.equals(this.refundReasons, refundData.refundReasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, onlyIndividuallyRefundable, refundReasons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundData {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    onlyIndividuallyRefundable: ").append(toIndentedString(onlyIndividuallyRefundable)).append("\n");
    sb.append("    refundReasons: ").append(toIndentedString(refundReasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
