/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An actual refund offer.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class RefundOffer {
  @JsonProperty("originalPrice")
  private Integer originalPrice = null;

  @JsonProperty("excess")
  private Integer excess = null;

  @JsonProperty("usedPart")
  private Integer usedPart = null;

  @JsonProperty("refundableAmount")
  private Integer refundableAmount = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("refundOfferId")
  private Long refundOfferId = null;

  public RefundOffer originalPrice(Integer originalPrice) {
    this.originalPrice = originalPrice;
    return this;
  }

   /**
   * The total original price of the refund offer. This is the total original price of all bookings for which a refund offer is requested.
   * @return originalPrice
  **/
  public Integer getOriginalPrice() {
    return originalPrice;
  }

  public void setOriginalPrice(Integer originalPrice) {
    this.originalPrice = originalPrice;
  }

  public RefundOffer excess(Integer excess) {
    this.excess = excess;
    return this;
  }

   /**
   * The excess of the refund offer.
   * @return excess
  **/
  public Integer getExcess() {
    return excess;
  }

  public void setExcess(Integer excess) {
    this.excess = excess;
  }

  public RefundOffer usedPart(Integer usedPart) {
    this.usedPart = usedPart;
    return this;
  }

   /**
   * The used part of the refund offer.
   * @return usedPart
  **/
  public Integer getUsedPart() {
    return usedPart;
  }

  public void setUsedPart(Integer usedPart) {
    this.usedPart = usedPart;
  }

  public RefundOffer refundableAmount(Integer refundableAmount) {
    this.refundableAmount = refundableAmount;
    return this;
  }

   /**
   * The refundable amount of the refund offer. This is the actual amount that can be refunded - taking into account the excess and the used part. If this refundable amount is 0, then nothing is refundable.
   * @return refundableAmount
  **/
  public Integer getRefundableAmount() {
    return refundableAmount;
  }

  public void setRefundableAmount(Integer refundableAmount) {
    this.refundableAmount = refundableAmount;
  }

  public RefundOffer currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency of the given prices and money amounts.
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public RefundOffer refundOfferId(Long refundOfferId) {
    this.refundOfferId = refundOfferId;
    return this;
  }

   /**
   * The refund offer id. This id can be used to prebook the refund offer.
   * @return refundOfferId
  **/
  public Long getRefundOfferId() {
    return refundOfferId;
  }

  public void setRefundOfferId(Long refundOfferId) {
    this.refundOfferId = refundOfferId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundOffer refundOffer = (RefundOffer) o;
    return Objects.equals(this.originalPrice, refundOffer.originalPrice) &&
        Objects.equals(this.excess, refundOffer.excess) &&
        Objects.equals(this.usedPart, refundOffer.usedPart) &&
        Objects.equals(this.refundableAmount, refundOffer.refundableAmount) &&
        Objects.equals(this.currency, refundOffer.currency) &&
        Objects.equals(this.refundOfferId, refundOffer.refundOfferId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalPrice, excess, usedPart, refundableAmount, currency, refundOfferId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundOffer {\n");
    
    sb.append("    originalPrice: ").append(toIndentedString(originalPrice)).append("\n");
    sb.append("    excess: ").append(toIndentedString(excess)).append("\n");
    sb.append("    usedPart: ").append(toIndentedString(usedPart)).append("\n");
    sb.append("    refundableAmount: ").append(toIndentedString(refundableAmount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    refundOfferId: ").append(toIndentedString(refundOfferId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
