/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The booked refund offer.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class RefundBooking {
  @JsonProperty("bookingId")
  private Long bookingId = null;

  @JsonProperty("savBookingId")
  private Long savBookingId = null;

  @JsonProperty("savTicketId")
  private Long savTicketId = null;

  public RefundBooking bookingId(Long bookingId) {
    this.bookingId = bookingId;
    return this;
  }

   /**
   * Booking id of the booking which contains the refunded ticket.
   * @return bookingId
  **/
  public Long getBookingId() {
    return bookingId;
  }

  public void setBookingId(Long bookingId) {
    this.bookingId = bookingId;
  }

  public RefundBooking savBookingId(Long savBookingId) {
    this.savBookingId = savBookingId;
    return this;
  }

   /**
   * Booking id of this refund booking.
   * @return savBookingId
  **/
  public Long getSavBookingId() {
    return savBookingId;
  }

  public void setSavBookingId(Long savBookingId) {
    this.savBookingId = savBookingId;
  }

  public RefundBooking savTicketId(Long savTicketId) {
    this.savTicketId = savTicketId;
    return this;
  }

   /**
   * Ticket id of the refund.
   * @return savTicketId
  **/
  public Long getSavTicketId() {
    return savTicketId;
  }

  public void setSavTicketId(Long savTicketId) {
    this.savTicketId = savTicketId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundBooking refundBooking = (RefundBooking) o;
    return Objects.equals(this.bookingId, refundBooking.bookingId) &&
        Objects.equals(this.savBookingId, refundBooking.savBookingId) &&
        Objects.equals(this.savTicketId, refundBooking.savTicketId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingId, savBookingId, savTicketId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundBooking {\n");
    
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    savBookingId: ").append(toIndentedString(savBookingId)).append("\n");
    sb.append("    savTicketId: ").append(toIndentedString(savTicketId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
