/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.Message;
import ch.sbb.app.b2p.client.Note;
import ch.sbb.app.b2p.client.Stop;
import ch.sbb.app.b2p.client.TransportProduct;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Aka Leg (aka J-S v3 PTRideLeg, AccessLeg, PTConnectionLeg).
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class Segment {
  /**
   * Type of Segment. PUBLIC_JOURNEY for public transportation by a TransportProduct; WALK_TRANSFER for a short walk to change between PUBLIC_JOURNEY Segments; TRANSFER any other
   */
  public enum TypeEnum {
    PUBLIC_JOURNEY("PUBLIC_JOURNEY"),
    WALK_TRANSFER("WALK_TRANSFER"),
    TRANSFER("TRANSFER");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("stops")
  private List<Stop> stops = new ArrayList<>();

  @JsonProperty("transportProduct")
  private TransportProduct transportProduct = null;

  @JsonProperty("attributes")
  private List<Note> attributes = new ArrayList<>();

  @JsonProperty("messages")
  private List<Message> messages = new ArrayList<>();

  @JsonProperty("direction")
  private String direction = null;

  /**
   * DEPRECATED: given on SegmentType.PUBLIC_JOURNEY only, but use Trip::isAlternative instead or assume PLANNED.
   */
  public enum JourneyStatusEnum {
    PLANNED("PLANNED"),
    ADDITIONAL("ADDITIONAL"),
    REPLACEMENT("REPLACEMENT"),
    SPECIAL("SPECIAL");

    private String value;

    JourneyStatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static JourneyStatusEnum fromValue(String input) {
      for (JourneyStatusEnum b : JourneyStatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("journeyStatus")
  private JourneyStatusEnum journeyStatus = null;

  @JsonProperty("cancelled")
  private Boolean cancelled = null;

  @JsonProperty("partiallyCancelled")
  private Boolean partiallyCancelled = null;

  @JsonProperty("reachable")
  private Boolean reachable = null;

  @JsonProperty("redirected")
  private Boolean redirected = null;

  public Segment type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Type of Segment. PUBLIC_JOURNEY for public transportation by a TransportProduct; WALK_TRANSFER for a short walk to change between PUBLIC_JOURNEY Segments; TRANSFER any other
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Segment stops(List<Stop> stops) {
    this.stops = stops;
    return this;
  }

  public Segment addStopsItem(Stop stopsItem) {
    this.stops.add(stopsItem);
    return this;
  }

   /**
   * All stops on a Segment.
   * @return stops
  **/
  public List<Stop> getStops() {
    return stops;
  }

  public void setStops(List<Stop> stops) {
    this.stops = stops;
  }

  public Segment transportProduct(TransportProduct transportProduct) {
    this.transportProduct = transportProduct;
    return this;
  }

   /**
   * Get transportProduct
   * @return transportProduct
  **/
  public TransportProduct getTransportProduct() {
    return transportProduct;
  }

  public void setTransportProduct(TransportProduct transportProduct) {
    this.transportProduct = transportProduct;
  }

  public Segment attributes(List<Note> attributes) {
    this.attributes = attributes;
    return this;
  }

  public Segment addAttributesItem(Note attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Additional information about the vehicle operating on a segment.
   * @return attributes
  **/
  public List<Note> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<Note> attributes) {
    this.attributes = attributes;
  }

  public Segment messages(List<Message> messages) {
    this.messages = messages;
    return this;
  }

  public Segment addMessagesItem(Message messagesItem) {
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Traffic-events on trip.
   * @return messages
  **/
  public List<Message> getMessages() {
    return messages;
  }

  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }

  public Segment direction(String direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Direction information. Represents the name of the last station of the associated transport-product&#x27;s journey.
   * @return direction
  **/
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public Segment journeyStatus(JourneyStatusEnum journeyStatus) {
    this.journeyStatus = journeyStatus;
    return this;
  }

   /**
   * DEPRECATED: given on SegmentType.PUBLIC_JOURNEY only, but use Trip::isAlternative instead or assume PLANNED.
   * @return journeyStatus
  **/
  public JourneyStatusEnum getJourneyStatus() {
    return journeyStatus;
  }

  public void setJourneyStatus(JourneyStatusEnum journeyStatus) {
    this.journeyStatus = journeyStatus;
  }

  public Segment cancelled(Boolean cancelled) {
    this.cancelled = cancelled;
    return this;
  }

   /**
   * true: journey is cancelled (default&#x3D;false)
   * @return cancelled
  **/
  public Boolean isCancelled() {
    return cancelled;
  }

  public void setCancelled(Boolean cancelled) {
    this.cancelled = cancelled;
  }

  public Segment partiallyCancelled(Boolean partiallyCancelled) {
    this.partiallyCancelled = partiallyCancelled;
    return this;
  }

   /**
   * true: journey is partially cancelled (default&#x3D;false)
   * @return partiallyCancelled
  **/
  public Boolean isPartiallyCancelled() {
    return partiallyCancelled;
  }

  public void setPartiallyCancelled(Boolean partiallyCancelled) {
    this.partiallyCancelled = partiallyCancelled;
  }

  public Segment reachable(Boolean reachable) {
    this.reachable = reachable;
    return this;
  }

   /**
   * true: journey is reachable (de: Anschluss kann gehalten werden, see TripV2::valid); false: de:nicht mehr erreichbare Fahrt
   * @return reachable
  **/
  public Boolean isReachable() {
    return reachable;
  }

  public void setReachable(Boolean reachable) {
    this.reachable = reachable;
  }

  public Segment redirected(Boolean redirected) {
    this.redirected = redirected;
    return this;
  }

   /**
   * true: journey is redirected
   * @return redirected
  **/
  public Boolean isRedirected() {
    return redirected;
  }

  public void setRedirected(Boolean redirected) {
    this.redirected = redirected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Segment segment = (Segment) o;
    return Objects.equals(this.type, segment.type) &&
        Objects.equals(this.stops, segment.stops) &&
        Objects.equals(this.transportProduct, segment.transportProduct) &&
        Objects.equals(this.attributes, segment.attributes) &&
        Objects.equals(this.messages, segment.messages) &&
        Objects.equals(this.direction, segment.direction) &&
        Objects.equals(this.journeyStatus, segment.journeyStatus) &&
        Objects.equals(this.cancelled, segment.cancelled) &&
        Objects.equals(this.partiallyCancelled, segment.partiallyCancelled) &&
        Objects.equals(this.reachable, segment.reachable) &&
        Objects.equals(this.redirected, segment.redirected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, stops, transportProduct, attributes, messages, direction, journeyStatus, cancelled, partiallyCancelled, reachable, redirected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Segment {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    stops: ").append(toIndentedString(stops)).append("\n");
    sb.append("    transportProduct: ").append(toIndentedString(transportProduct)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    journeyStatus: ").append(toIndentedString(journeyStatus)).append("\n");
    sb.append("    cancelled: ").append(toIndentedString(cancelled)).append("\n");
    sb.append("    partiallyCancelled: ").append(toIndentedString(partiallyCancelled)).append("\n");
    sb.append("    reachable: ").append(toIndentedString(reachable)).append("\n");
    sb.append("    redirected: ").append(toIndentedString(redirected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
