/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.LocalizedDescription;
import ch.sbb.app.b2p.client.RouteInformation;
import ch.sbb.app.b2p.client.Station;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * Information about the tariff. The only mandatory attributes are valid from and valid to and at least one element in product description, including description of the product and the language in which the description is formulated. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class TariffInformation {
  @JsonProperty("description")
  private LocalizedDescription description = null;

  @JsonProperty("productNumber")
  private Integer productNumber = null;

  @JsonProperty("qualityOfService")
  private Integer qualityOfService = null;

  @JsonProperty("reduced")
  private Boolean reduced = null;

  @JsonProperty("origin")
  private Station origin = null;

  @JsonProperty("destination")
  private Station destination = null;

  @JsonProperty("routeInformations")
  private List<RouteInformation> routeInformations = null;

  @JsonProperty("fqCode")
  private String fqCode = null;

  /**
   * The direction of this journey.
   */
  public enum DirectionEnum {
    OUTWARD("outward"),
    RETURN("return"),
    ROUND("round");

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DirectionEnum fromValue(String input) {
      for (DirectionEnum b : DirectionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("direction")
  private DirectionEnum direction = null;

  @JsonProperty("validFromDate")
  private OffsetDateTime validFromDate = null;

  @JsonProperty("validToDate")
  private OffsetDateTime validToDate = null;

  @JsonProperty("returnJourneyFromDate")
  private OffsetDateTime returnJourneyFromDate = null;

  @JsonProperty("returnJourneyToDate")
  private OffsetDateTime returnJourneyToDate = null;

  @JsonProperty("customerSegment")
  private LocalizedDescription customerSegment = null;

  public TariffInformation description(LocalizedDescription description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public LocalizedDescription getDescription() {
    return description;
  }

  public void setDescription(LocalizedDescription description) {
    this.description = description;
  }

  public TariffInformation productNumber(Integer productNumber) {
    this.productNumber = productNumber;
    return this;
  }

   /**
   * The number of the product
   * @return productNumber
  **/
  public Integer getProductNumber() {
    return productNumber;
  }

  public void setProductNumber(Integer productNumber) {
    this.productNumber = productNumber;
  }

  public TariffInformation qualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
    return this;
  }

   /**
   * The quality of service
   * @return qualityOfService
  **/
  public Integer getQualityOfService() {
    return qualityOfService;
  }

  public void setQualityOfService(Integer qualityOfService) {
    this.qualityOfService = qualityOfService;
  }

  public TariffInformation reduced(Boolean reduced) {
    this.reduced = reduced;
    return this;
  }

   /**
   * Reduced price for serviceIt is possible to generate reduced fare (half-fare and others) according to three possible formats:* Boolean reduced (TariffInformation) * String customerSegment (PassengerInformation) * String reductionText (PassengerInformation)These three possibilities are technically not mutually exclusive but the combined effects are not well defined
   * @return reduced
  **/
  public Boolean isReduced() {
    return reduced;
  }

  public void setReduced(Boolean reduced) {
    this.reduced = reduced;
  }

  public TariffInformation origin(Station origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin
  **/
  public Station getOrigin() {
    return origin;
  }

  public void setOrigin(Station origin) {
    this.origin = origin;
  }

  public TariffInformation destination(Station destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  public Station getDestination() {
    return destination;
  }

  public void setDestination(Station destination) {
    this.destination = destination;
  }

  public TariffInformation routeInformations(List<RouteInformation> routeInformations) {
    this.routeInformations = routeInformations;
    return this;
  }

  public TariffInformation addRouteInformationsItem(RouteInformation routeInformationsItem) {
    if (this.routeInformations == null) {
      this.routeInformations = new ArrayList<>();
    }
    this.routeInformations.add(routeInformationsItem);
    return this;
  }

   /**
   * Informations about the route.
   * @return routeInformations
  **/
  public List<RouteInformation> getRouteInformations() {
    return routeInformations;
  }

  public void setRouteInformations(List<RouteInformation> routeInformations) {
    this.routeInformations = routeInformations;
  }

  public TariffInformation fqCode(String fqCode) {
    this.fqCode = fqCode;
    return this;
  }

   /**
   * The FQ Code of this product.
   * @return fqCode
  **/
  public String getFqCode() {
    return fqCode;
  }

  public void setFqCode(String fqCode) {
    this.fqCode = fqCode;
  }

  public TariffInformation direction(DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

   /**
   * The direction of this journey.
   * @return direction
  **/
  public DirectionEnum getDirection() {
    return direction;
  }

  public void setDirection(DirectionEnum direction) {
    this.direction = direction;
  }

  public TariffInformation validFromDate(OffsetDateTime validFromDate) {
    this.validFromDate = validFromDate;
    return this;
  }

   /**
   * The desired start date of validity.
   * @return validFromDate
  **/
  public OffsetDateTime getValidFromDate() {
    return validFromDate;
  }

  public void setValidFromDate(OffsetDateTime validFromDate) {
    this.validFromDate = validFromDate;
  }

  public TariffInformation validToDate(OffsetDateTime validToDate) {
    this.validToDate = validToDate;
    return this;
  }

   /**
   * The desired end date of validity.
   * @return validToDate
  **/
  public OffsetDateTime getValidToDate() {
    return validToDate;
  }

  public void setValidToDate(OffsetDateTime validToDate) {
    this.validToDate = validToDate;
  }

  public TariffInformation returnJourneyFromDate(OffsetDateTime returnJourneyFromDate) {
    this.returnJourneyFromDate = returnJourneyFromDate;
    return this;
  }

   /**
   * The desired start date of the return journey.
   * @return returnJourneyFromDate
  **/
  public OffsetDateTime getReturnJourneyFromDate() {
    return returnJourneyFromDate;
  }

  public void setReturnJourneyFromDate(OffsetDateTime returnJourneyFromDate) {
    this.returnJourneyFromDate = returnJourneyFromDate;
  }

  public TariffInformation returnJourneyToDate(OffsetDateTime returnJourneyToDate) {
    this.returnJourneyToDate = returnJourneyToDate;
    return this;
  }

   /**
   * The desired end date of the return journey.
   * @return returnJourneyToDate
  **/
  public OffsetDateTime getReturnJourneyToDate() {
    return returnJourneyToDate;
  }

  public void setReturnJourneyToDate(OffsetDateTime returnJourneyToDate) {
    this.returnJourneyToDate = returnJourneyToDate;
  }

  public TariffInformation customerSegment(LocalizedDescription customerSegment) {
    this.customerSegment = customerSegment;
    return this;
  }

   /**
   * Get customerSegment
   * @return customerSegment
  **/
  public LocalizedDescription getCustomerSegment() {
    return customerSegment;
  }

  public void setCustomerSegment(LocalizedDescription customerSegment) {
    this.customerSegment = customerSegment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TariffInformation tariffInformation = (TariffInformation) o;
    return Objects.equals(this.description, tariffInformation.description) &&
        Objects.equals(this.productNumber, tariffInformation.productNumber) &&
        Objects.equals(this.qualityOfService, tariffInformation.qualityOfService) &&
        Objects.equals(this.reduced, tariffInformation.reduced) &&
        Objects.equals(this.origin, tariffInformation.origin) &&
        Objects.equals(this.destination, tariffInformation.destination) &&
        Objects.equals(this.routeInformations, tariffInformation.routeInformations) &&
        Objects.equals(this.fqCode, tariffInformation.fqCode) &&
        Objects.equals(this.direction, tariffInformation.direction) &&
        Objects.equals(this.validFromDate, tariffInformation.validFromDate) &&
        Objects.equals(this.validToDate, tariffInformation.validToDate) &&
        Objects.equals(this.returnJourneyFromDate, tariffInformation.returnJourneyFromDate) &&
        Objects.equals(this.returnJourneyToDate, tariffInformation.returnJourneyToDate) &&
        Objects.equals(this.customerSegment, tariffInformation.customerSegment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, productNumber, qualityOfService, reduced, origin, destination, routeInformations, fqCode, direction, validFromDate, validToDate, returnJourneyFromDate, returnJourneyToDate, customerSegment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TariffInformation {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    productNumber: ").append(toIndentedString(productNumber)).append("\n");
    sb.append("    qualityOfService: ").append(toIndentedString(qualityOfService)).append("\n");
    sb.append("    reduced: ").append(toIndentedString(reduced)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    routeInformations: ").append(toIndentedString(routeInformations)).append("\n");
    sb.append("    fqCode: ").append(toIndentedString(fqCode)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    validFromDate: ").append(toIndentedString(validFromDate)).append("\n");
    sb.append("    validToDate: ").append(toIndentedString(validToDate)).append("\n");
    sb.append("    returnJourneyFromDate: ").append(toIndentedString(returnJourneyFromDate)).append("\n");
    sb.append("    returnJourneyToDate: ").append(toIndentedString(returnJourneyToDate)).append("\n");
    sb.append("    customerSegment: ").append(toIndentedString(customerSegment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
