/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.Link;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * The ticket data request.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class TicketInfo {
  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("ticketId")
  private Long ticketId = null;

  @JsonProperty("externalTicketId")
  private String externalTicketId = null;

  @JsonProperty("externalTicketReference")
  private String externalTicketReference = null;

  @JsonProperty("preBookingId")
  private Long preBookingId = null;

  public TicketInfo links(List<Link> links) {
    this.links = links;
    return this;
  }

  public TicketInfo addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Context information required by the services.
   * @return links
  **/
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public TicketInfo ticketId(Long ticketId) {
    this.ticketId = ticketId;
    return this;
  }

   /**
   * ID of the booked ticket.
   * @return ticketId
  **/
  public Long getTicketId() {
    return ticketId;
  }

  public void setTicketId(Long ticketId) {
    this.ticketId = ticketId;
  }

  public TicketInfo externalTicketId(String externalTicketId) {
    this.externalTicketId = externalTicketId;
    return this;
  }

   /**
   * The external booking ID.
   * @return externalTicketId
  **/
  public String getExternalTicketId() {
    return externalTicketId;
  }

  public void setExternalTicketId(String externalTicketId) {
    this.externalTicketId = externalTicketId;
  }

  public TicketInfo externalTicketReference(String externalTicketReference) {
    this.externalTicketReference = externalTicketReference;
    return this;
  }

   /**
   * The external booking reference that is printed on the ticket.
   * @return externalTicketReference
  **/
  public String getExternalTicketReference() {
    return externalTicketReference;
  }

  public void setExternalTicketReference(String externalTicketReference) {
    this.externalTicketReference = externalTicketReference;
  }

  public TicketInfo preBookingId(Long preBookingId) {
    this.preBookingId = preBookingId;
    return this;
  }

   /**
   * ID of the prebooking that has been booked.
   * @return preBookingId
  **/
  public Long getPreBookingId() {
    return preBookingId;
  }

  public void setPreBookingId(Long preBookingId) {
    this.preBookingId = preBookingId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketInfo ticketInfo = (TicketInfo) o;
    return Objects.equals(this.links, ticketInfo.links) &&
        Objects.equals(this.ticketId, ticketInfo.ticketId) &&
        Objects.equals(this.externalTicketId, ticketInfo.externalTicketId) &&
        Objects.equals(this.externalTicketReference, ticketInfo.externalTicketReference) &&
        Objects.equals(this.preBookingId, ticketInfo.preBookingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, ticketId, externalTicketId, externalTicketReference, preBookingId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketInfo {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    ticketId: ").append(toIndentedString(ticketId)).append("\n");
    sb.append("    externalTicketId: ").append(toIndentedString(externalTicketId)).append("\n");
    sb.append("    externalTicketReference: ").append(toIndentedString(externalTicketReference)).append("\n");
    sb.append("    preBookingId: ").append(toIndentedString(preBookingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
