/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specific vehicle operating on a segment (aka J-S v3 ServiceProduct).
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class TransportProduct {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("categoryShortForm")
  private String categoryShortForm = null;

  @JsonProperty("categoryLongForm")
  private String categoryLongForm = null;

  @JsonProperty("line")
  private String line = null;

  @JsonProperty("number")
  private String number = null;

  /**
   * Type of vehicle of the transport-product.
   */
  public enum VehicleTypeEnum {
    BOAT("BOAT"),
    BUS("BUS"),
    CABLE("CABLE"),
    METRO("METRO"),
    TRAIN("TRAIN"),
    TRAMWAY("TRAMWAY"),
    CHAIRLIFT("CHAIRLIFT"),
    COG_RAILWAY("COG_RAILWAY"),
    TAXI("TAXI"),
    LIFT("LIFT"),
    AIRPLANE("AIRPLANE");

    private String value;

    VehicleTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static VehicleTypeEnum fromValue(String input) {
      for (VehicleTypeEnum b : VehicleTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("vehicleType")
  private VehicleTypeEnum vehicleType = null;

  public TransportProduct name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Operator specific name of vehicle. Displayable to end-consumer.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TransportProduct categoryShortForm(String categoryShortForm) {
    this.categoryShortForm = categoryShortForm;
    return this;
  }

   /**
   * Operator specific short name of category. Known examples (no closed list): &#x27;BEX&#x27;, &#x27;CNL&#x27;, &#x27;EC&#x27;, &#x27;EN&#x27;, &#x27;GEX&#x27;, &#x27;IC&#x27;, &#x27;ICE&#x27;, &#x27;ICN&#x27;, &#x27;IR&#x27;, &#x27;RE&#x27;, &#x27;RJ&#x27;, &#x27;RX&#x27;, &#x27;SN&#x27;, &#x27;TGV&#x27;, &#x27;VAE&#x27;
   * @return categoryShortForm
  **/
  public String getCategoryShortForm() {
    return categoryShortForm;
  }

  public void setCategoryShortForm(String categoryShortForm) {
    this.categoryShortForm = categoryShortForm;
  }

  public TransportProduct categoryLongForm(String categoryLongForm) {
    this.categoryLongForm = categoryLongForm;
    return this;
  }

   /**
   * Operator specific long name of category.
   * @return categoryLongForm
  **/
  public String getCategoryLongForm() {
    return categoryLongForm;
  }

  public void setCategoryLongForm(String categoryLongForm) {
    this.categoryLongForm = categoryLongForm;
  }

  public TransportProduct line(String line) {
    this.line = line;
    return this;
  }

   /**
   * Operator specific line of the vehicle.
   * @return line
  **/
  public String getLine() {
    return line;
  }

  public void setLine(String line) {
    this.line = line;
  }

  public TransportProduct number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Operator specific number of the vehicle.
   * @return number
  **/
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public TransportProduct vehicleType(VehicleTypeEnum vehicleType) {
    this.vehicleType = vehicleType;
    return this;
  }

   /**
   * Type of vehicle of the transport-product.
   * @return vehicleType
  **/
  public VehicleTypeEnum getVehicleType() {
    return vehicleType;
  }

  public void setVehicleType(VehicleTypeEnum vehicleType) {
    this.vehicleType = vehicleType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransportProduct transportProduct = (TransportProduct) o;
    return Objects.equals(this.name, transportProduct.name) &&
        Objects.equals(this.categoryShortForm, transportProduct.categoryShortForm) &&
        Objects.equals(this.categoryLongForm, transportProduct.categoryLongForm) &&
        Objects.equals(this.line, transportProduct.line) &&
        Objects.equals(this.number, transportProduct.number) &&
        Objects.equals(this.vehicleType, transportProduct.vehicleType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, categoryShortForm, categoryLongForm, line, number, vehicleType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransportProduct {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    categoryShortForm: ").append(toIndentedString(categoryShortForm)).append("\n");
    sb.append("    categoryLongForm: ").append(toIndentedString(categoryLongForm)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    vehicleType: ").append(toIndentedString(vehicleType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
