/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.EcoBalance;
import ch.sbb.app.b2p.client.Link;
import ch.sbb.app.b2p.client.Segment;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * A one-way trip from an origin to a destination (may contain a via) with its segments and stops.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class Trip {
  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("tripId")
  private String tripId = null;

  @JsonProperty("alternative")
  private Boolean alternative = null;

  @JsonProperty("valid")
  private Boolean valid = null;

  @JsonProperty("segments")
  private List<Segment> segments = new ArrayList<>();

  @JsonProperty("searchHint")
  private String searchHint = null;

  @JsonProperty("scrollCheckSum")
  private String scrollCheckSum = null;

  @JsonProperty("ecoBalance")
  private EcoBalance ecoBalance = null;

  public Trip links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Trip addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Context information required by the services.
   * @return links
  **/
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public Trip tripId(String tripId) {
    this.tripId = tripId;
    return this;
  }

   /**
   * Describing trip-context for this journey (do not think of a permanent &#x27;tripId&#x27; because it is only a temporary snapshot of a trip, which might be changed by realtime aspects drastically - by means up to non-rideable at all - any time).
   * @return tripId
  **/
  public String getTripId() {
    return tripId;
  }

  public void setTripId(String tripId) {
    this.tripId = tripId;
  }

  public Trip alternative(Boolean alternative) {
    this.alternative = alternative;
    return this;
  }

   /**
   * false: original connection; true: realtime alternative
   * @return alternative
  **/
  public Boolean isAlternative() {
    return alternative;
  }

  public void setAlternative(Boolean alternative) {
    this.alternative = alternative;
  }

  public Trip valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * true: Trip is still possible to ride based on the current realtime situation (related to LegV2::reachable); false: not rideable as a &#x27;whole&#x27; Trip&#x27; anymore. Important: if this valid toggles from true to false, the passenger might not be able to perform his Trip, by means re-planning options might occur.
   * @return valid
  **/
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }

  public Trip segments(List<Segment> segments) {
    this.segments = segments;
    return this;
  }

  public Trip addSegmentsItem(Segment segmentsItem) {
    this.segments.add(segmentsItem);
    return this;
  }

   /**
   * The segments of the trip and its stops.
   * @return segments
  **/
  public List<Segment> getSegments() {
    return segments;
  }

  public void setSegments(List<Segment> segments) {
    this.segments = segments;
  }

  public Trip searchHint(String searchHint) {
    this.searchHint = searchHint;
    return this;
  }

   /**
   * A hint/explanation is given if Trip was not found by a direct (first) search. In such a case origin/destination might not match exactly to request parameters.
   * @return searchHint
  **/
  public String getSearchHint() {
    return searchHint;
  }

  public void setSearchHint(String searchHint) {
    this.searchHint = searchHint;
  }

  public Trip scrollCheckSum(String scrollCheckSum) {
    this.scrollCheckSum = scrollCheckSum;
    return this;
  }

   /**
   * Checksum of the trip to filter same results on client side after scroll requests.
   * @return scrollCheckSum
  **/
  public String getScrollCheckSum() {
    return scrollCheckSum;
  }

  public void setScrollCheckSum(String scrollCheckSum) {
    this.scrollCheckSum = scrollCheckSum;
  }

  public Trip ecoBalance(EcoBalance ecoBalance) {
    this.ecoBalance = ecoBalance;
    return this;
  }

   /**
   * Get ecoBalance
   * @return ecoBalance
  **/
  public EcoBalance getEcoBalance() {
    return ecoBalance;
  }

  public void setEcoBalance(EcoBalance ecoBalance) {
    this.ecoBalance = ecoBalance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trip trip = (Trip) o;
    return Objects.equals(this.links, trip.links) &&
        Objects.equals(this.tripId, trip.tripId) &&
        Objects.equals(this.alternative, trip.alternative) &&
        Objects.equals(this.valid, trip.valid) &&
        Objects.equals(this.segments, trip.segments) &&
        Objects.equals(this.searchHint, trip.searchHint) &&
        Objects.equals(this.scrollCheckSum, trip.scrollCheckSum) &&
        Objects.equals(this.ecoBalance, trip.ecoBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, tripId, alternative, valid, segments, searchHint, scrollCheckSum, ecoBalance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trip {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    alternative: ").append(toIndentedString(alternative)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    segments: ").append(toIndentedString(segments)).append("\n");
    sb.append("    searchHint: ").append(toIndentedString(searchHint)).append("\n");
    sb.append("    scrollCheckSum: ").append(toIndentedString(scrollCheckSum)).append("\n");
    sb.append("    ecoBalance: ").append(toIndentedString(ecoBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
