/*
 * Swiss Mobility API (B2P API)
 * <p>The SBB Swiss Mobility API is an interface that you can integrate into your own distribution system. Timetable and fare details are made available to you via this interface. Initially, we are introducing SBB Swiss Mobilty API for Swiss domestic transport services, but we will be constantly developing it and adding new products and functions. There are two ways to use the service:</p><ul><li>Either integrate the SBB Swiss Mobility API as a full version, so that bookings are made directly via your distribution environment</li><li>Or use the Affiliate solution, with a link to the SBB webshop or SBB mobile</li></ul><p>Before you request access to our API, please get in contact with SBB Digital Affiliates by sending an email stating your intentions and goal. Please note that the purpose of our API is to generate sales turnover through it. Retrieving timetables and prices only is not permitted due to the Look2Book Ratio. Please check out our <a href=\"https://company.sbb.ch/en/sbb-as-business-partner/services/digital-sales-solutions/sales-solutions/sbb-swiss-mobility-api/sbb-swiss-mobility-api-gtc.html\">GTC</a> as well. On the right you can find the contact details and the links to the important websites.</p>
 *
 * OpenAPI spec version: 3.20.23
 * Contact: digitalsales@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.sbb.app.b2p.client;

import java.util.Objects;
import java.util.Arrays;
import ch.sbb.app.b2p.client.Area;
import ch.sbb.app.b2p.client.ZoneValidityArea;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Contains area information at the departure or destination (or both) of the trip
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-17T11:44:18.538712800+02:00[Europe/Zurich]")
public class ValidityArea {
  @JsonProperty("leadingArea")
  private Area leadingArea = null;

  @JsonProperty("tailingArea")
  private Area tailingArea = null;

  @JsonProperty("zoneValidityArea")
  private ZoneValidityArea zoneValidityArea = null;

  public ValidityArea leadingArea(Area leadingArea) {
    this.leadingArea = leadingArea;
    return this;
  }

   /**
   * Get leadingArea
   * @return leadingArea
  **/
  public Area getLeadingArea() {
    return leadingArea;
  }

  public void setLeadingArea(Area leadingArea) {
    this.leadingArea = leadingArea;
  }

  public ValidityArea tailingArea(Area tailingArea) {
    this.tailingArea = tailingArea;
    return this;
  }

   /**
   * Get tailingArea
   * @return tailingArea
  **/
  public Area getTailingArea() {
    return tailingArea;
  }

  public void setTailingArea(Area tailingArea) {
    this.tailingArea = tailingArea;
  }

  public ValidityArea zoneValidityArea(ZoneValidityArea zoneValidityArea) {
    this.zoneValidityArea = zoneValidityArea;
    return this;
  }

   /**
   * Get zoneValidityArea
   * @return zoneValidityArea
  **/
  public ZoneValidityArea getZoneValidityArea() {
    return zoneValidityArea;
  }

  public void setZoneValidityArea(ZoneValidityArea zoneValidityArea) {
    this.zoneValidityArea = zoneValidityArea;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidityArea validityArea = (ValidityArea) o;
    return Objects.equals(this.leadingArea, validityArea.leadingArea) &&
        Objects.equals(this.tailingArea, validityArea.tailingArea) &&
        Objects.equals(this.zoneValidityArea, validityArea.zoneValidityArea);
  }

  @Override
  public int hashCode() {
    return Objects.hash(leadingArea, tailingArea, zoneValidityArea);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidityArea {\n");
    
    sb.append("    leadingArea: ").append(toIndentedString(leadingArea)).append("\n");
    sb.append("    tailingArea: ").append(toIndentedString(tailingArea)).append("\n");
    sb.append("    zoneValidityArea: ").append(toIndentedString(zoneValidityArea)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
