# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  sbbConnector:
    uri: https://b2p.app.sbb.ch
    contractId: DEMO
    clientId: DEMO
    clientSecret: DEMO
    tokenEndpoint: DEMO
    scope: DEMO
