name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v5
    secrets:
      mvnArgs: -DjourneyUri=${{ secrets.JOURNEY_URI }} -DclientId=${{ secrets.CLIENT_ID }}
